### ISSUE TITLE
hubspot.crm.contacts.exceptions.ApiTypeError: Got an unexpected keyword argument 'id_property' to method get_by_id

### ISSUE THREAD

**Issue by JStrebeyko** [HubSpot/hubspot-api-python#100]
Hi there 👋 

First of, thanks for creating this amazing CRM tool, is fire 🔥

We just updated Python HubSpot API Client on hour backend noticed that our flow broke. Apparently, we have problems retrieving customer data using email.

> An email address is the primary unique identifier for a contact in HubSpot. (...) To update a contact via the API, you can use either the contact ID or the contact's email.

[The docs](https://developers.hubspot.com/docs/api/crm/contacts#endpoint?spec=GET-/crm/v3/objects/contacts) make it seem customer id and email can be used interchangeably, but it does not seem the case anymore. For our use-case we utilized the `.get_by_id()` method with the  `id_property` kwarg, but it seems to have been discontinued.

> The idProperty parameter doesn't appear on the Endpoints tab due to technical limitations, but it can be used for contacts exclusively with email. To use an email address as the unique identifier, set the idProperty as email and enter the email address in place of the contact ID.

We failed to find adequate documentation on python SDK and its usage of `idProperty`, getting the error in the issue title instead. The lecture of the codebase makes me believe `.get_by_id()` function cannot be used for it, while the HubSpot API in the dashboard does match emails with ids and correctly returns sought object.

Could you please advise me & my colleagues on how exactly to retrieve a contact using email-only?

Cheers! 🍻

**Comment by kiyoqoko** [comment]
Try the following

`api_client.crm.objects.basic_api.get_by_id("contact", "email@example.com", id_property="email")`

**Comment by gleberdiniz** [comment]
@kiyoqoko id_property got removed on version 5.0.0:
https://github.com/HubSpot/hubspot-api-python/blob/v5.0.0/hubspot/crm/contacts/api/basic_api.py#L249
on 4.0.6 id_property param was there: https://github.com/HubSpot/hubspot-api-python/blob/v4.0.6/hubspot/crm/contacts/api/basic_api.py#L286

anyone knows an alternative? this is a bug?

**Comment by kiyoqoko** [comment]
@gleberdiniz I understand it has been removed and its most probably a bug but I am suggesting using `objects.basic_api` as an alternative, where the `id_property` is still available: https://github.com/HubSpot/hubspot-api-python/blob/b4147f756bb614dee43a7ba022ac0b6fa26ef91c/hubspot/crm/objects/api/basic_api.py#L279

**Comment by JStrebeyko** [comment]
Hi there @kiyoqoko, @gleberdiniz

Thanks for answering my question! I can confirm that using `basic_api.get_by_id` with email on contacts works, thanks a lot! :beers:

The ticket should be considered solved, I just have one more thing to ask, perhaps not worth another issue:

Our HubSpot tracks the unique user id's, mapped to our DB records. It'd shorten the loop to query them directly, but when we use some other `id_propery` other than `email`, the  `basic_api.get_by_id` returns a `400`:
> "Contacts may only be looked up by 'email' as part of a unique property value request"
The user id cannot be made unique in HubSpot Dashboard, saying
> "This feauture isn't supported for contacts yet"

Do I get it correctly, that currently contacts can be queried with email only?

Thanks

**Comment by plaurynovich-hubspot** [comment]
Hi, @JStrebeyko. It should work again without a workaround since v5.1.0. Thank you.
