### ISSUE TITLE
ImportError: cannot import name 'Hubspot' from 'hubspot'

### ISSUE THREAD

**Issue by ivo-1** [HubSpot/hubspot-api-python#102]
Hello,

I am trying to set up an API call to HubSpot but even the import from the README fails for me.

```
from hubspot import Hubspot
```

```
ImportError: cannot import name 'Hubspot' from 'hubspot' (/opt/homebrew/anaconda3/envs/hubspot-env/lib/python3.9/site-packages/hubspot/__init__.py)
```

I have set up a fresh environment and only installed the HubSpot API client as instructed:
```
pip install --upgrade hubspot-api-client
```

The installation seems to be successful:
```
$ conda list
<some other stuff>
hubspot-api-client        5.0.0                    pypi_0    pypi
```

Note that my file is not called `hubspot.py` (like in #63) and I have not installed the unofficial HubSpot wrapper like in #94. 

I am using macOS on a machine with the M1 chip. Could that maybe be the issue?

Please let me know if you need anything else!

**Comment by Eric-Mindspark** [comment]
Per the readme it is HubSpot not Hubspot:

from hubspot import HubSpot

**Comment by ivo-1** [comment]
Thank you! 🤦
