### ISSUE TITLE
last_activity_date for a contact as a property and contacts grouped by a company

### ISSUE THREAD

**Issue by devangmehta123** [HubSpot/hubspot-api-python#106]
Hi,

I have been trying out this sdk for a few days. I have been looking for an example which shows how properties are fetched.

For example, if I do something like `all_contacts = api_client.crm.contacts.get_all(properties=['id'])`, that seems to work. 

If I don't set the properties, I can see the default properties but not the custom properties for the contact. I can get custom properties if I set the properties but that forces me to set the default properties along with the custom properties.

Lastly, I cannot seem to get last_activity_date as a property while setting the properties. Is there something that I am doing wrong here?

Here is a use case which is very interesting for me. Let's say that I have a contact. I wish to find all the other contact ids which are associated with the same company which this contact is associated with. Is there is a simple way to do that using this SDK?

Thanks.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @devangmehta123
In properties `last_activity_date` is specified as `notes_last_updated`,
Your request should be likes something like this:
`all_contacts = api_client.crm.contacts.get_all(properties=['notes_last_updated'])`,

If I get your case right, here the example:
```python
import hubspot
from pprint import pprint

client = hubspot.Client.create(access_token="YOUR_ACCESS_TOKEN")

associated_companies_with_contact = client.crm.contacts.associations_api.get_all(
    contact_id="contact_id",
    to_object_type="companies",
    limit=500
).results

associated_contacts_with_company = client.crm.companies.associations_api.get_all(
    # company id for which you want to know the contacts associated with it
    company_id=associated_companies_with_contact[0].to_object_id,
    to_object_type="contacts", limit=500
).results

contact_ids = [contact.to_object_id for contact in associated_contacts_with_company]
pprint(contact_ids)
```
I hope it will be useful for you.
