### ISSUE TITLE
Pulling objectLists

### ISSUE THREAD

**Issue by swagluke** [HubSpot/hubspot-api-python#108]
Inside Hubspot's GUI, there is a Lists option under Contacts, which allows you to create filters to apply to companies or contacts.
![image](https://user-images.githubusercontent.com/7270414/173670590-54d7ba2b-c562-4f98-bacc-71ead7efc413.png)

The URL looks like this
https://app.hubspot.com/contacts/0000000/objectLists/0000?query=company

Is it possible to pull such list using the Python API? I've tried really hard to look into the code base but couldn't figure it out.

Thanks in advance.

**Comment by plaurynovich-hubspot** [comment]
Hi, @swagluke. I'm afraid this SDK supports [Hubspot V3 API](https://developers.hubspot.com/docs/api/overview) only. But you can apply your filters with [Search API](https://developers.hubspot.com/docs/api/crm/search) if you need it. Thank you.

**Comment by swagluke** [comment]
@plaurynovich-hubspot 
Thank you for the quick response.
![image](https://user-images.githubusercontent.com/7270414/173910011-38fbe10a-5e3c-498f-82d2-8b17ae81b3d2.png)

These are the filters that I have created in order to get the objectlists of companies. Could you provide a quick python example of how I can utilize the ```api_client.crm.contacts.search_api```?
A few lines of python code would be greatly appreciated.

Thank you so much
