### ISSUE TITLE
Properties Name

### ISSUE THREAD

**Issue by andreian02** [HubSpot/hubspot-api-python#12]
Given this example previously, 
api_response = client.crm.contacts.get_all(properties=["firstname", "lastname", "email", "address"])

is there a list of properties and their naming convention to use with this api? 

Thank you, 
Andrei

**Comment by atanasiuk-hubspot** [comment]
Hi, @andreian02 

You can request a list of properties with:
```
client.crm.properties.core_api.get_all(object_type="CONTACTS")
```

**Comment by andreian02** [comment]
Hello atanasiuk 

Thank you!
