### ISSUE TITLE
Drop unsupported versions of Python like 3.5 and 3.6

### ISSUE THREAD

**Issue by cclauss** [HubSpot/hubspot-api-python#121]
There are important improvements that this codebase cannot take advantage of because it continues to support Python 3.5 and 3.6.  https://devguide.python.org/versions

https://nedbatchelder.com/text/which-py.html
https://pythonspeed.com/articles/stop-using-python-3.6

**Comment by plaurynovich-hubspot** [comment]
It should be fixed since v6.0.0. Thank you.
