### ISSUE TITLE
Customizing the properties returned from get_all() function for companies,contacts,deals

### ISSUE THREAD

**Issue by mparthasarathy25** [HubSpot/hubspot-api-python#122]
Is there any to change the properties outputted when using the get_all function? There are multiple columns of data in hubspot that I would like to be returned, but when I use the get_all function, these columns' values are not being returned.

**Comment by plaurynovich-hubspot** [comment]
Hi @mparthasarathy25. You can specify properties that you'd like to get by passing properties param. 
```python
from hubspot import HubSpot

api_client = HubSpot(access_token='your_access_token')
contacts = api_client.crm.contacts.get_all(properties=["email", "firstname"])

print(contacts)
```
Thank you.
