### ISSUE TITLE
Question about marketing.transactional.single_send_api

### ISSUE THREAD

**Issue by DragosChirila** [HubSpot/hubspot-api-python#127]
Hi,

I am trying to send a transactional email. I am creating a payload like in the docs here https://developers.hubspot.com/docs/api/marketing/transactional-emails and my code looks like this:
```
from hubspot import HubSpot

api_client = HubSpot(access_token=<my access token>)

payload={
    'emailId': '<email ID>',
    'message': {'to': '<email address>'},
}

result = (
    api_client.marketing.transactional
    .single_send_api
    .send_email(payload)
)
```

and I get:
`TypeError: SingleSendApi.send_email() takes 1 positional argument but 2 were given`

If I try like this:
```
result = (
    api_client.marketing.transactional
    .single_send_api
    .send_email(data=payload)
)
```
I get:
`hubspot.marketing.transactional.exceptions.ApiTypeError: Got an unexpected keyword argument 'data' to method send_email`

Could you please indicate how to call this method? :)

Regards,
Dragos

**Comment by plaurynovich-hubspot** [comment]
Hi @DragosChirila. You can try something like this:
```python
from hubspot import HubSpot
from hubspot.marketing.transactional import PublicSingleSendRequestEgg

api_client = HubSpot(access_token=<my access token>)

payload={
    'emailId': '<email ID>',
    'message': {'to': '<email address>'},
}

egg = PublicSingleSendRequestEgg(payload)

result = (
    api_client.marketing.transactional
    .single_send_api
    .send_email(public_single_send_request_egg=egg)
)
```
Thank you.

**Comment by DragosChirila** [comment]
Hey @plaurynovich-hubspot ,

Thank you very much for your answer.

Indeed, using `PublicSingleSendRequestEgg` did the trick but the code that worked for me is:
```
payload={
    'email_id': '<email ID>',
    'message': {'to': <email address>'},
    'custom_properties': {
        'user_firstname': 'Dragos',
    }
}

egg = PublicSingleSendRequestEgg(**payload) # <--- not (payload)
```

All good, thanks again.

Dragos
