### ISSUE TITLE
all engagements for all contacts 

### ISSUE THREAD

**Issue by ElianoMarques** [HubSpot/hubspot-api-python#13]
Hi, is there a way to collect all engagements related to a list of contacts?

**Comment by atanasiuk-hubspot** [comment]
Hi, @ElianoMarques, according to [API docs](https://developers.hubspot.com/docs/api/crm/engagements), the Engagements API is currently in development.

**Comment by ElianoMarques** [comment]
@atanasiuk-hubspot, is there a way to get all engagements for a given contact using this library?

**Comment by atanasiuk-hubspot** [comment]
Sorry, didn't get the question right.

You may take a look at [Associations API](https://developers.hubspot.com/docs/api/crm/associations). 

The following sample will request engagements associated with a given contact:

```
from hubspot.crm.associations import BatchInputPublicObjectId, PublicObjectId

batch_input_public_object_id = BatchInputPublicObjectId(
    inputs=[PublicObjectId(id=101)]
)
api_response = hubspot_client.crm.associations.batch_api.read(
    "CONTACTS",
    "ENGAGEMENTS",
    batch_input_public_object_id=batch_input_public_object_id
)
```

**Comment by ElianoMarques** [comment]
ok thank you. to the 101 is the contact id. thanks

**Comment by atanasiuk-hubspot** [comment]
> ok thank you. to the 101 is the contact id. I've tired with a different ID and i see 4 engagements but no detail about each engagement. @atanasiuk-hubspot is there a way to also parse the detail about the engagement itself?

I believe this is something https://developers.hubspot.com/docs/api/crm/engagements could provide when it's ready

**Comment by ElianoMarques** [comment]
ok thank you. Marketing Ads would also be part of the roadmap via the api? I saw there Marketing API?

**Comment by atanasiuk-hubspot** [comment]
> ok thank you. Marketing Ads would also be part of the roadmap via the api? I saw there Marketing API?

Marketing APIs are also on the roadmap

**Comment by ElianoMarques** [comment]
@atanasiuk-hubspot sorry for asking again but is there a timeline for the ability to access marketing and forms data ? is there any way to load this automatically with any type of api?

**Comment by viktorbrech** [comment]
This is the current stable version of the Forms API, including endpoints for forms per se and for form submissions: https://legacydocs.hubspot.com/docs/methods/forms/forms_overview

The Web Analytics API also includes an eventType "e_submitted_form" (i.e. a form submission, albeit without the contents of the individual form fields) https://developers.hubspot.com/docs/api/events/web-analytics

What other marketing data are you looking to access?
