### ISSUE TITLE
Line item association attribute error

### ISSUE THREAD

**Issue by cvassios-eibach** [HubSpot/hubspot-api-python#131]
Getting an error `AttributeError: 'AssociationsApi' object has no attribute 'items_line_item_id_associations_to_object_type_to_object_id_association_type'`

When trying to make an association using the example from https://developers.hubspot.com/docs/api/crm/line-items

api_response = client.crm.line_items.associations_api.**items_line_item_id_associations_to_object_type_to_object_id_association_type**(...)

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @cvassios-eibach 
Here the worked code
<img width="589" alt="Снимок экрана 2022-12-23 в 16 00 05" src="https://user-images.githubusercontent.com/119863330/209340491-2feadb3d-02ff-4688-8ff2-fb5b54d3cd5f.png">
Thank you.
