### ISSUE TITLE
batch association method doesn't support pagination and return not more than 100 records 

### ISSUE THREAD

**Issue by bisibuka** [HubSpot/hubspot-api-python#135]
hubspot.crm.associations.batch_api.read needs to support pagination

**Comment by plaurynovich-hubspot** [comment]
Hi, @bisibuka. It looks like the API does not support pagination. 100 records is an API limit as well. Thank you.

**Comment by bisibuka** [comment]
it does support

**Comment by plaurynovich-hubspot** [comment]
Do you mean v4 associations? They are not supported, yet, but I'm sure that they will be. Thank you.

**Comment by bisibuka** [comment]
No. Here is the example. I call https://api.hubapi.com/crm/v3/associations/company/contact/batch/read
and get 
`{'status': 'COMPLETE', 'results': [{'from': {'id': '6465999056'}, 'to': [{'id': '6101', 'type': 'company_to_contact'}, {'id': '6102', 'type': 'company_to_contact'}, ... {'id': '7455', 'type': 'company_to_contact'}, {'id': '7501', 'type': 'company_to_contact'}, {'id': '7502', 'type': 'company_to_contact'}], 'paging': {'next': {'after': 'MC0yLTc1MDI%3D', 'link': 'https://api.hubapi.com/crm/v3/objects/0-2/6465999056/associations/0-1?portalId=26190935&after=MC0yLTc1MDI%3D'}}}], 'startedAt': '2022-11-10T13:46:24.038Z', 'completedAt': '2022-11-10T13:46:24.048Z'}`
