### ISSUE TITLE
postal_mail endpoint missing from crm.objects

### ISSUE THREAD

**Issue by bakobako** [HubSpot/hubspot-api-python#136]
Hey,

In the documentation of the Hubspot API : https://developers.hubspot.com/docs/api/crm/postal-mail there is a code snippet on how to use this python SDK to fetch data from the Postal Mail endpoint:

`api_response = client.crm.objects.postal_mail.basic_api.mail(limit=10, archived=False)`

However, I do not see this implemented here. Is this going to be implemented any time soon?

If I fork this and make a pull request to add the endpoint will it be accepted?

Thanks

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @bakobako 
Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.2.0)?
Thank you.
