### ISSUE TITLE
Feedbacks API still only using HSAPI key

### ISSUE THREAD

**Issue by ac-slater-rr** [HubSpot/hubspot-api-python#137]
It looks like all of the API's under feedback_submissions is still only using api key authentication. For example:
[basic_api.py](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/crm/objects/feedback_submissions/api/basic_api.py)
[search_api.py](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/crm/objects/feedback_submissions/api/search_api.py)

`auth_settings = ["hapikey"]  # noqa: E501 `

I believe this needs to be changed to include oauth2 as well:
`auth_settings = ["hapikey", "oauth2"]`

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @ac-slater-rr. We working on it.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @ac-slater-rr. Could you check the latest version 7.0.0. Thanks.
