### ISSUE TITLE
get_all doesnt bring details around lead source 

### ISSUE THREAD

**Issue by ElianoMarques** [HubSpot/hubspot-api-python#14]
Hi, 
the contacts.get_all function does indeed bring all contacts however it doesn't take into account two columns in the contacts schema: Lead Status and Lead Source Detail. 

Those are two important attributes and i'm not sure how to add them to the get_all function. Is there a way? 

Thank you, 
Eliano

**Comment by atanasiuk-hubspot** [comment]
Hi, @ElianoMarques 

You should manually pass a list of properties you'd like to receive:

```
client.crm.contacts.get_all(
    properties=["hs_lead_status", "email"],
)
```

To get a list of available properties in a system you can with:
```
client.crm.properties.core_api.get_all(
    object_type="CONTACTS"
)

**Comment by atanasiuk-hubspot** [comment]
Closing this. Feel free to reopen if any questions
