### ISSUE TITLE
Contact Association Fails with Empty Body

### ISSUE THREAD

**Issue by chibenny** [HubSpot/hubspot-api-python#142]
I'm not sure if I'm using a deprecated bit of code, but while updating to use private apps for authentication (and the general updates that come along with it) - creating contact associations seems to have broken.
```python
client = hubspot.HubSpot(access_token=HUBSPOT_API_TEST_KEY)
linking = client.crm.contacts.associations_api.create(
    contact_id=<contact_id>,
    to_object_type='Companies',
    to_object_id=<company_id>,
    association_type='contact_to_company'
)
```
Gives a response of:
```HTTP response body: {"status":"error","message":"Invalid JSON input: a request body was expected, but none found" [ ... ]```

And sure enough, [it seems we're calling the v4 endpoint and explicitly sending no body](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/crm/contacts/api/associations_api.py#L259-L272), which according to the docs (and the error), is expecting a payload.

If there's another way of creating associations with this library, I haven't found it.
Any update or clarity appreciated.

**Comment by cdelacombaz** [comment]
I encountered the same issue and managed to create associations like:

```py
from hubspot.crm.associations.models.batch_input_public_association import BatchInputPublicAssociation

def assign_contact_to_deal(self, contact_id, deal_id):
      batch_input_public_association = BatchInputPublicAssociation(
          inputs=[{"from": {"id": deal_id}, "to": {"id": contact_id}, "type": "deal_to_contact"}])
      try:
          api_response = self.client.crm.associations.batch_api.create(
              from_object_type="deal",
              to_object_type="contact",
              batch_input_public_association=batch_input_public_association
          )
          return api_response
      except ApiException as e:
          print("Exception when calling batch_api->create: %s\n" % e)
```
