### ISSUE TITLE
Fetch all records with history not allowed because of limits

### ISSUE THREAD

**Issue by barbarosydev** [HubSpot/hubspot-api-python#143]
Currently it is not possible to get all records if you need properties with history.

`hubspot.crm.companies.exceptions.ApiException: (400)
Reason: Bad Request
HTTP response headers: HTTPHeaderDict({'Date': 'Mon, 21 Nov 2022 13:22:06 GMT', 'Content-Type': 'application/json;charset=utf-8', 'Content-Length': '227', 'Connection': 'keep-alive', 'CF-Ray': '76d9bb6eecb2aca9-TXL', 'Strict-Transport-Security': 'max-age=31536000; includeSubDomains; preload', 'Vary': 'origin, Accept-Encoding', 'CF-Cache-Status': 'DYNAMIC', 'Access-Control-Allow-Credentials': 'false', 'X-HubSpot-Correlation-Id': '20eb2a82-676a-480f-8a7d-ed380e924b70', 'X-HubSpot-RateLimit-Daily': '500000', 'X-HubSpot-RateLimit-Daily-Remaining': '498677', 'X-HubSpot-RateLimit-Interval-Milliseconds': '10000', 'X-HubSpot-RateLimit-Max': '150', 'X-HubSpot-RateLimit-Remaining': '149', 'X-HubSpot-RateLimit-Secondly': '15', 'X-HubSpot-RateLimit-Secondly-Remaining': '14', 'X-Trace': '2BFE28CACB730295D03F5A3D59798A5F80DC90E80C000000000000000000', 'Report-To': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s="}],"group":"cf-nel","max_age":604800}', 'NEL': '{"success_fraction":0.01,"report_to":"cf-nel","max_age":604800}', 'Server': 'cloudflare', 'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'})
HTTP response body: {"status":"error","message":"You can only request at most 50 objects in one request for properties with history.","correlationId":"20eb2a82-676a-480f-8a7d-ed380e924b70","context":{"limit":["100"]},"category":"VALIDATION_ERROR"}
`

**Comment by SethN-reforge** [comment]
I have got this working locally by changing MAX_PAGE_SIZE to 50 on my local machine
https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/utils/objects.py#L1

Perhaps a PR enhancement could be made to allow this MAX_PAGE_SIZE setting to be overridable somehow?

**Comment by regit** [comment]
Got the same issue.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone
Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.4.0)?

**Comment by regit** [comment]
I can set the limit correctly with the latest version and use the get_all function.
