### ISSUE TITLE
HubDB API does not seem to authenticate properly

### ISSUE THREAD

**Issue by woutwoot** [HubSpot/hubspot-api-python#15]
With this code:
``` 
hubspot = HubSpot(api_key='...')
hubspot.cms.hubdb.default_api.get_all_tables()
```
I get an error in response:
```
Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview
```

Am I doing something wrong or is this a bug?

**Comment by atanasiuk-hubspot** [comment]
Hi, @woutwoot!

> Am I doing something wrong or is this a bug?

Seems to be a bug (OAuth token is only supported by SDK for now). Will keep you posted on this.

**Comment by atanasiuk-hubspot** [comment]
HubSpot API key is now supported in the [latest](https://github.com/HubSpot/hubspot-api-python/releases/tag/v3.3.0) SDK release.

**Comment by woutwoot** [comment]
Thanks! The API now works as expected via API key.
