### ISSUE TITLE
CRM Deals date format bug

### ISSUE THREAD

**Issue by teemu47** [HubSpot/hubspot-api-python#150]
Hi,

`api_client.crm.deals.get_all()` and `api_client.crm.deals.basic_api.get_page()` functions returns the `created_at` and `updated_at` fields in a weird format. For example ` 'created_at': datetime.datetime(2021, 1, 28, 13, 44, 43, 318000, tzinfo=tzutc())`. 

What is the best way to convert the response to json? `json.dumps()` fails with an error 
```
Object of type datetime is not JSON serializable
```

**Comment by teemu47** [comment]
Here's a workaround for the problem 
```python
    result = []

    api_client = HubSpot(access_token=api_key)
    response = api_client.crm.deals.get_all()

    for deal in response:
        formatted_deal = deal.to_dict()
        formatted_deal["created_at"] = formatted_deal["created_at"].isoformat()
        formatted_deal["updated_at"] = formatted_deal["updated_at"].isoformat()
        result.append(formatted_deal)

    return result
```

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @teemu47 
Could you try to using `json.dump` like this:
```python
json.dumps(dict_obj, default=str)
```
Perhaps this information will be useful to you.
