### ISSUE TITLE
Cannot update contact by email?

### ISSUE THREAD

**Issue by PrashantSedhain** [HubSpot/hubspot-api-python#151]
I am trying to update the contact by email instead of contact id but I can't find that method at all.
<img width="793" alt="Screenshot 2022-12-14 at 12 59 48 PM" src="https://user-images.githubusercontent.com/49375658/207688189-2d441714-14d4-41fd-a6b5-a429dee4eaf9.png">

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @PrashantSedhain 
Can you try this one? 
<img width="601" alt="Снимок экрана 2022-12-15 в 17 08 43" src="https://user-images.githubusercontent.com/119863330/207882720-e0c9796c-cbe9-4798-a079-794682ddbfaf.png">
Thank you.

**Comment by PrashantSedhain** [comment]
Thanks a bumch! I really appreciate your response. I actually went through the code of the library and figured out what I should do to get it working yesterday. I am sure the above one works too. 
<img width="845" alt="Screenshot 2022-12-15 at 8 29 48 AM" src="https://user-images.githubusercontent.com/49375658/207886740-92fa0e26-5414-4bf1-9223-d670eb375254.png">
