### ISSUE TITLE
ImportError: cannot import name 'ObjectType' from 'hubspot.crm' since 7.1.0

### ISSUE THREAD

**Issue by rw6bsc** [HubSpot/hubspot-api-python#159]
Hello,

I need to update this library to at least Version 7.1.0.
However since updating I get the error:
`ImportError: cannot import name 'ObjectType' from 'hubspot.crm'`

Version 7.0.0 was stable, so the breaking change was introduced in 7.1.0
If that was intended, please advise me how I should access the ObjectTypes from now on.
Otherwise, I hope you find the time to fix this in the next update.

Possibly related:
https://github.com/HubSpot/hubspot-api-python/issues/74
https://github.com/HubSpot/hubspot-api-python/issues/60

Best regards and happy new year.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @rw6bsc.
Thank you for reporting this issue.
Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.2.2)?

**Comment by rw6bsc** [comment]
Hello @alzheltkovskiy-hubspot.
Yes the latest (7.2.2) Version works again.
Thank you very much for fixing it this fast! :)
