### ISSUE TITLE
bool data type in PropertyCreate class

### ISSUE THREAD

**Issue by Skorpyon** [HubSpot/hubspot-api-python#16]
Looks like `bool` type is missed.

**Comment by atanasiuk-hubspot** [comment]
Hi, @Skorpyon 

According to [CRM Properties](https://developers.hubspot.com/docs/api/crm/properties) docs, one possible option to specify bool is a combination of:
- `type="enumeration"`
- `field_type="booleancheckbox"`

Please check if this is what you need.

**Comment by Skorpyon** [comment]
Hey @atanasiuk-hubspot 

Yes, I created checkbox property using Hubspot web interface, download it using API and understood that it should be like you described above. Sure I surprised that boolean is a string in Hubspot... But I have no choice probably :) Thank you for your response. You may close issue I think.

**Comment by atanasiuk-hubspot** [comment]
Nice to hear! Feel free to re-open if any updates.
