### ISSUE TITLE
List All Standard Object Schemas?

### ISSUE THREAD

**Issue by gbeaven90** [HubSpot/hubspot-api-python#164]
According to the [API docs](https://developers.hubspot.com/docs/api/crm/crm-custom-objects) there is an endpoint `/crm/v3/schemas` to "Get all schemas" for custom objects. Is there an equivalent endpoint to list all of the standard object schemas as well?

**Comment by lorenzobrasil** [comment]
Do you mean an endpoint to get you all the default Hubspot object properties? [Here](https://developers.hubspot.com/docs/api/crm/properties) you may find general details about the properties api section.
And [the first endpoint](https://developers.hubspot.com/docs/api/crm/properties) `GET /crm/v3/properties/{objectType}` will deliver you the properties of the object specified.

**Comment by Just-Drue** [comment]
I'm a bit confused on how to retrieve object properties as well. From tinkering with the client my best guess is that it should be something like:

`client.crm.contacts.basic_api.api_client.call_api(
    "/crm/v3/properties/contacts", 
    "GET",
    header_params={"Authorization": "Bearer <user-token>"}
)`

Which isn't any different than using a simple `requests` lib to achieve the same thing? Hopefully, I'm missing something very obvious here.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone
The simplest way to get all properties looks something like this:
```python
import hubspot
from pprint import pprint

client = hubspot.Client.create(access_token="YOUR_ACCESS_TOKEN")
api_response = client.crm.properties.core_api.get_all(object_type="needed_object", archived=False)
pprint(api_response)
```
