### ISSUE TITLE
How to submit parameters to get_page_with_http_info method

### ISSUE THREAD

**Issue by chriseal** [HubSpot/hubspot-api-python#17]
hi there, 

Is there a way to get all contacts and  provide parameters listed on the API - https://legacydocs.hubspot.com/docs/methods/contacts/get_contacts ?

I'm currently using this:
```
client = HubSpot(api_key=self.API_KEY)
all_contacts = client.crm.contacts.get_all()
```

Which I think calls the `get_page_with_http_info` method here: hubspot-api-python/hubspot/crm/contacts/api/basic_api.py . In that documentation, I only see properties and associations as lists, but can't control...
- Property Mode | &propertyMode=x 
- Form Submission Mode | &formSubmissionMode=x 
- List Memberships | &showListMemberships=x 
...as listed in the documentation. 

Is that correct? I'm trying to loosely get 'all the information about all the contacts' or as close to that as possible. Is there currently a way to do that or no?

thanks!
Chris

**Comment by chriseal** [comment]
UPDATE: I tried calling .get_all with properties specified and got the following error. I must've misread the code. It appears there is no way to specify properties list either in the `get_all` method.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-1a5c3cfbe162> in <module>
      1 all_contacts = client.crm.contacts.get_all({
----> 2     'properties': [d['name'] for d in contact_properties]
      3 })

TypeError: get_all() takes 1 positional argument but 2 were given
```

**Comment by atanasiuk-hubspot** [comment]
Hi, @chriseal!

You should be able to pass any parameters to `get_all` method which are available for [Get Page](https://developers.hubspot.com/docs/api/crm/contacts) API endpoint as keyword arguments:

```
all_contacts = client.crm.contacts.get_all(
    properties=[d['name'] for d in contact_properties]
)
```

**Comment by chriseal** [comment]
Got it. Looks like I was referencing the wrong version of the API! thanks @atanasiuk-hubspot
