### ISSUE TITLE
Unable to Associate Line Items to Deals Using Python

### ISSUE THREAD

**Issue by cvassios-eibach** [HubSpot/hubspot-api-python#172]
Hello,
I've ran into an issue associating line items to deals via the python API. When looking at the documentation (https://developers.hubspot.com/docs/api/crm/line-items), it shows I should use:

```
import hubspot
from pprint import pprint
from hubspot.crm.line_items import ApiException

client = hubspot.Client.create(access_token="YOUR_ACCESS_TOKEN")

try:
api_response = client.crm.line_items.associations_api.get_all(line_item_id=100, to_object_type="toObjectType", limit=500)
pprint(api_response)
except ApiException as e:
print("Exception when calling associations_api->get_all: %s\n" % e)
```

But when I run my file, I get an error saying:

`"TypeError: create() missing 1 required positional argument: 'association_type'"`

I have added that in (even though it isn't mentioned in the docs), and get a new error:

`"hubspot.crm.line_items.exceptions.ApiTypeError: Got an unexpected keyword argument 'association_spec' to method create"`

Even though association_spec is in the docs.

If I remove association_spec, I get a third error:

```
"hubspot.crm.line_items.exceptions.ApiException: (404)
Reason: Not Found"
```

I have posted this issue in the community forum (https://community.hubspot.com/t5/APIs-Integrations/Unable-to-Associate-Line-Item-to-Deal/td-p/751555), but have not been able to get a solution.

Hubspot support informed me I should create an issue here.

I ran a test in Postman with the old API and the line item was added, so it appears to just be v3 using python. 

We have this working with another system using v3 with cURL, however the issue is occurring on a separate system that I can only run python on.

**Comment by cvassios-eibach** [comment]
I just updated my Hubspot client libraries and now I get a new error

```
hubspot.crm.line_items.exceptions.ApiException: (405)
Reason: Method Not Allowed
```

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @cvassios-eibach 
Could you check your SDK version?
I checked the latest version [7.3.1](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.3.1) and it works well.

**Comment by cvassios-eibach** [comment]
Hi @alzheltkovskiy-hubspot 
I ran `pip freeze` and it shows `hubspot-api-client==7.3.1`

**Comment by alzheltkovskiy-hubspot** [comment]
HI @cvassios-eibach 
Could you check from what place importing library Hubspot?
This place:
```python
import hubspot
```
Maybe it is a local import?

**Comment by cvassios-eibach** [comment]
@alzheltkovskiy-hubspot 
I'm not sure I understand what you mean, but I ran `pip show hubspot` and it showing its installed the same place all my other modules are installed `c:\users\cvassios\anaconda3\lib\site-packages`. 

```
>pip show hubspot
Name: hubspot
Version: 0.1.14.dev0
Summary: UNKNOWN
Home-page: UNKNOWN
Author: UNKNOWN
Author-email: UNKNOWN
License: LICENSE.txt
Location: c:\users\cvassios\anaconda3\lib\site-packages
Requires:
Required-by:
```

**Comment by alzheltkovskiy-hubspot** [comment]
@cvassios-eibach 
This is exactly what I wanted to know.
Could you try something like this?
```python
pip uninstall hubspot
pip uninstall hubspot-api-client
pip install hubspot-api-client  
```

**Comment by cvassios-eibach** [comment]
@alzheltkovskiy-hubspot 
I ran those commands, now when I try to run my file, I get an error saying:
`ModuleNotFoundError: No module named 'hubspot.crm'; 'hubspot' is not a package`

Don't I need `hubspot` according to the docs?
![Screenshot_18](https://user-images.githubusercontent.com/47762679/220677074-ab1e8bd6-8938-4dea-97ef-ee7c3d374db4.png)

**Comment by alzheltkovskiy-hubspot** [comment]
@cvassios-eibach 
It looks like you do not have a virtual environment configured and your `import hubspot` is trying to get not the hubspot that is in the environment, but some local one, perhaps the file you are running is located in a directory that has the same name

**Comment by cvassios-eibach** [comment]
@alzheltkovskiy-hubspot I have never configured a virtual environment before. Also I had the rest of my requests (creating/association contacts, deals and products) working prior to this issue, but now those all show this same error.

**Comment by alzheltkovskiy-hubspot** [comment]
Try to follow the steps to configure your [environment](https://www.geeksforgeeks.org/set-up-virtual-environment-for-python-using-anaconda/). Make sure there are no directories in your project structure that could conflict with the `hubspot` name. And try this workable example:
```python
import hubspot
from pprint import pprint
from hubspot.crm.line_items import ApiException

client = hubspot.Client.create(access_token="YOUR_ACCESS_TOKEN")


try:
    api_response = client.crm.line_items.associations_api.get_all(
        line_item_id="existing_line_item_id", to_object_type="deals", limit=500
    )
    pprint(api_response)
except ApiException as e:
    print("Exception when calling associations_api->get_all: %s\n" % e)

```

**Comment by cvassios-eibach** [comment]
@alzheltkovskiy-hubspot , sorry I was out of the office for a few days.

I created a new environment following the documentation, but when I ran `conda install -n yourenvname hubspot-api-client` it says that package isn't available.

```
PackagesNotFoundError: The following packages are not available from current channels:

  - hubspot-api-client
```

**Comment by alzheltkovskiy-hubspot** [comment]
@cvassios-eibach, this problem is not related to the work of the SDK, as far as I understand the problem is related to the fact that your virtual environment does not work quite correctly, you should solve this problem first.
