### ISSUE TITLE
docker-compose command for sample apps was crashing

### ISSUE THREAD

**Issue by alyshareinard** [HubSpot/hubspot-api-python#18]
When running: docker-compose up --build web
in the sample apps, I was getting an error (see bottom of this issue).  

I was able to fix it by adding:
ADD /sample-apps/oauth-app/README.md /sdk/

to the Dockerfile before the WORKDIR /sdk/ command

Error:

Creating network "rate-limit-app_default" with the default driver
Building web
Step 1/12 : FROM python:3.8
 ---> 9756fa8d7b9d
Step 2/12 : RUN mkdir -p /sdk
 ---> Using cache
 ---> d504848a32af
Step 3/12 : ADD ./hubspot /sdk/hubspot
 ---> Using cache
 ---> a2a9478a4011
Step 4/12 : ADD ./setup.py VERSION /sdk/
 ---> Using cache
 ---> 68c0d6307383
Step 5/12 : WORKDIR /sdk
 ---> Using cache
 ---> 820a681f7c2a
Step 6/12 : RUN pip install -e .
 ---> Running in 7ea5e6d88101
Obtaining file:///sdk
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/sdk/setup.py'"'"'; __file__='"'"'/sdk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1licyj80
         cwd: /sdk/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/sdk/setup.py", line 34, in <module>
        with open(DIR_PATH + "/README.md", "r", encoding="utf-8") as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/sdk/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Service 'web' failed to build : The command '/bin/sh -c pip install -e .' returned a non-zero code: 1

**Comment by atanasiuk-hubspot** [comment]
Hi, @alyshareinard, thank you for the report. This should be fixed now.
