### ISSUE TITLE
Missing custom object endpoints

### ISSUE THREAD

**Issue by hub-lenf** [HubSpot/hubspot-api-python#184]
Hello everyone! 

I noticed there is a new page for CRM Custom objects with many endpoints, as we can see in this link:
[https://developers.hubspot.com/docs/api/crm/crm-custom-objects](url)

However, it seems some of the methods are not implemented, such as: 

- SimplePublicObjectInputForCreate;
- BatchInputSimplePublicObjectInputForCreate.

I would appreciate it very much if these would be implemented any time soon.

Best regards,
L.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @hub-lenf.
Thanks for your issue. This is a small inaccuracy in the documentation. You need to use the `SimplePublicObjectInput` instead of `SimplePublicObjectInputForCreate` and `BatchInputSimplePublicObjectInput` instead of `BatchInputSimplePublicObjectInputForCreate`. Could you try this option and write what you got? We will fix documentation as soon as we can.

**Comment by trofimovm** [comment]
I have the same problem. use example from the documentation:

`import hubspot
from pprint import pprint
from hubspot.crm.objects.notes import SimplePublicObjectInputForCreate, ApiException

client = hubspot.Client.create(access_token="YOUR_ACCESS_TOKEN")

properties = {
    "hs_timestamp": "2023-03-22T03:30:17.883Z",
    "hs_note_body": "Spoke with decision maker john",
    "hubspot_owner_id": "174878294"
}
simple_public_object_input_for_create = SimplePublicObjectInputForCreate(properties=properties, associations=[{"to":{"id":"60451"},"types":[{"associationCategory":"HUBSPOT_DEFINED","associationTypeId":202}]}])
try:
    api_response = client.crm.objects.notes.basic_api.create(simple_public_object_input_for_create=simple_public_object_input_for_create)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling basic_api->create: %s\n" % e)`
    
error when I use this example in my project:    
    
    `Traceback (most recent call last):
  File "/Users/mikhailtrofimov/code/asales/main.py", line 12, in <module>
    from hubspot.crm.objects.notes import SimplePublicObjectInputForCreate, ApiException
ImportError: cannot import name 'SimplePublicObjectInputForCreate' from 'hubspot.crm.objects.notes' (/Users/mikhailtrofimov/code/asales/venv/lib/python3.9/site-packages/hubspot/crm/objects/notes/__init__.py)
`


Version of hubspot: 0.1.14.dev0

**Comment by trofimovm** [comment]
While SimplePublicObjectInput has not been fixed, we can use requests directly to the API. However, we would like SimplePublicObjectInput to be fixed or for the documentation to explain how it should work.
```
def add_note_to_contact(contact_id, note, responsible_manager_crm_id):

    current_time = datetime.utcnow()
    formatted_time = current_time.strftime("%Y-%m-%dT%H:%M:%S.%f")[:-3] + "Z"
    url = "https://api.hubapi.com/crm/v3/objects/notes"
    headers = {
        "authorization": "Bearer " + access_token,
        "content-type": "application/json",
    }
    data = {
        "properties": {
            "hs_timestamp": formatted_time,
            "hs_note_body": note,
            "hubspot_owner_id": responsible_manager_crm_id,
        },
        "associations": [
            {
                "to": {
                    "id": contact_id,
                },
                "types": [
                    {
                        "associationCategory": "HUBSPOT_DEFINED",
                        "associationTypeId": 202,
                    }
                ],
            }
        ],
    }

    response = requests.post(url, headers=headers, data=json.dumps(data))

    print(response.status_code)
```

**Comment by michaelmota** [comment]
Any fixes on this?
