### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by jude9apple** [HubSpot/hubspot-api-python#191]
Hi,

I would like to use hubspot-api-client python Library, Following this tutorial : [hubspot-api-client · PyPI](https://pypi.org/project/hubspot-api-client/)

I was able to install the Library, but the next step is not working, saying that hubspot is an unresolved reference
from hubspot import HubSpot

I am using the interpreter from ArcGIS Pro, python version 3.9. 

What am I missing ?

Thanks,

Juliette

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @jude9apple.
I have just used the code from the example and for me, it works well. Perhaps it is the peculiarities `ArcGIS Pro`.
