### ISSUE TITLE
Associations v4 endpoints gone in v8

### ISSUE THREAD

**Issue by RaduG** [HubSpot/hubspot-api-python#192]
According to the [changelog](https://github.com/HubSpot/hubspot-api-python/blob/19e6697fd57b11ed09cf27fb79bcd1a375737a12/CHANGELOG.md?plain=1#L25:L27), a number of associations endpoints were removed in the latest SDK, as well as the OpenAPI spec of the API. However, the removed endpoints still work today and they are still part of the official developer documentation.

I also raised the same [here](https://community.hubspot.com/t5/APIs-Integrations/Associations-v4-endpoints-disappeared-from-OpenAPI-spec-and/td-p/783127) without success. Are you able to advise please?

**Comment by RaduG** [comment]
@alzheltkovskiy-hubspot would you be able to help please?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @RaduG.
We are aware of this problem and working on it. It will be fixed as soon as we can. Thanks for your issue.

**Comment by RaduG** [comment]
Thanks! Please keep me posted here.

**Comment by RaduG** [comment]
Hi @alzheltkovskiy-hubspot, do you have any updates? Given that the endpoints are live but the OpenAPI spec is broken for clients, it sounds like it's something that should be fixable relatively quickly. This is a major problem for us, as we generate the SDK ourselves from the OpenAPI spec because this package doesn't support asyncio, and we're now stuck.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @RaduG. We are currently dependent on another team's work and have been given a rough deadline. Maybe by the end of the week, this issue will be resolved.

**Comment by RaduG** [comment]
Hi @alzheltkovskiy-hubspot any updates? Thanks!

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @RaduG. Yes, we added [beta version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v8.0.0-beta-5) and after some validations we going to release version 8.0.0 next week.

**Comment by peterhadrian** [comment]
@alzheltkovskiy-hubspot, I believe I'm having an issue related to this but wanted to confirm. When using python Custom Code in a workflow, I'm getting an import module error when importing `hubspot.crm.associations.v4`. See below for the import code and the resulting error.

```
import os, hubspot
from hubspot import HubSpot
from hubspot.crm.contacts import PublicObjectSearchRequest, ApiException
from hubspot.crm.associations.v4 import ApiException
```

```
[ERROR] Runtime.ImportModuleError: Unable to import module 'hubspotHandler': No module named 'hubspot.crm.associations.v4'
Traceback (most recent call last):
Memory: 52/128 MB
Runtime: 1.25 ms
```

This is odd behavior given this is the exact import command used in the official documentation for the Associations endpoint [here](https://developers.hubspot.com/docs/api/crm/associations).

Is this being addressed? And what should I do in the meantime to be able to create associations via Custom Code in a workflow?

**Comment by pembo13** [comment]
Any followup on this? The CHANGELOG says that `crm.contacts.associations_api` was removed, but there is no documentation saying what replaces it.

**Comment by pembo13** [comment]
Are there any code samples that show how to use v4 API for associations?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone! Could you check the latests [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v9.0.0)?
