### ISSUE TITLE
Raise more specific exceptions during signature validation

### ISSUE THREAD

**Issue by engstrom** [HubSpot/hubspot-api-python#198]
The new `Signature` class raises two exceptions currently.

- One is [a ValueError](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/utils/signature.py#L62)
- nd the other is [an instance of Python's base Exception class](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/utils/signature.py#L24).

It would be more helpful if this class raised a custom exception [like the prior signature validation method does](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/utils/webhooks.py#L26).

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @engstrom. Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/tree/v8.0.0-beta-6)?

**Comment by dustin-engstrom** [comment]
@alzheltkovskiy-hubspot That looks great! Thank you!
