### ISSUE TITLE
API exception error while retrieving Hubspot contacts

### ISSUE THREAD

**Issue by maheshsonavane** [HubSpot/hubspot-api-python#20]
We are trying to get the contacts information. We want to get all the properties associated with the contact. 
We get API exception error intermittently. Could you please suggest how do we handle this?

<img width="1093" alt="hubspot error" src="https://user-images.githubusercontent.com/45288730/99351384-7b2b4100-28c6-11eb-8adf-a5e902c6d808.png">

**Comment by atanasiuk-hubspot** [comment]
Hi, @maheshsonavane, this looks like an API error. Could you maybe provide a server response from output with `correlation-id` included?

**Comment by maheshsonavane** [comment]
Hi @atanasiuk-hubspot ,
I get below error while retrieving contacts. I've highlighted the correlation-id and error message in yellow. Could you please help?

![image](https://user-images.githubusercontent.com/45288730/120150597-df7d7480-c208-11eb-9d54-5b3f9b4cc690.png)

**Comment by atanasiuk-hubspot** [comment]
That means you've reached your API rate limit (429 HTTP code) and should wait some time before doing new requests
