### ISSUE TITLE
v3 contact properties history, form submissions and list memberships

### ISSUE THREAD

**Issue by jesusenlanet** [HubSpot/hubspot-api-python#21]
Hi

I'm wondering if I can retrieve the custom property history for a contact.
The v1 allow that in multiple ways, the one I was using was [getting a batch of contacts by id ](https://legacydocs.hubspot.com/docs/methods/contacts/get_batch_by_vid).

Also I was getting the form submission and listing the memberships, the params I was using:
```
propertyMode=value_and_history
formSubmissionMode=all
showListMemberships=true
```

But reading the v3 documentation looks that properties historic is not returned anymore.
Is that feature available? If not, that behavior will be ported to v3 in the future?

Also I want to know if possible when will be dropped the v1 contacts endpoint, if is planned to be dropped.

Thanks.

**Comment by atanasiuk-hubspot** [comment]
Hi, @jesusenlanet 

> I'm wondering if I can retrieve the custom property history for a contact.

At this moment API doesn't provide property history

> Also I want to know if possible when will be dropped the v1 contacts endpoint, if is planned to be dropped.

No plans to drop the v1 API, it's going to be supported
