### ISSUE TITLE
Extensions API does not work with private apps and the new access token

### ISSUE THREAD

**Issue by ume-daniel** [HubSpot/hubspot-api-python#211]
import hubspot
api_client = hubspot.Client.create(access_token=<my access token>)
api_client.crm.extensions.videoconferencing.settings_api.get_by_id(app_id=<my app id>)

HTTP response body: {"status":"error","message":"Authentication credentials not found. This API supports both API Key and OAuth 2.0 authentication and you can find more details at https://developers.hubspot.com/docs/methods/auth/oauth-overview","correlationId":"4acd14cf-ade6-4d82-a58c-4a7b4f0e40cd","category":"INVALID_AUTHENTICATION"}

**Comment by alzheltkovskiy-hubspot** [comment]
HI @ume-daniel. If i understand correctly, you trying to use `access_token` instead `hubspot api key`. [Here](https://developers.hubspot.com/docs/api/developer-tools-overview) is the information on how to obtain an `API key`.

**Comment by ume-daniel** [comment]
The page you reference says that the extension api is part of private apps. The page for the [video conference api](https://developers.hubspot.com/docs/api/crm/extensions/video-conferencing) specifically states:
You can use the access token from your [private app](https://developers.hubspot.com/docs/api/private-apps) to authenticate the request.

I had tried to use the older API key methods but that fails.

Have you confirmed this works?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @ume-daniel. For me this request works well:
```python
api_client = hubspot.Client.create(api_key="My_hubspot_api_key")
api_client.crm.extensions.videoconferencing.settings_api.get_by_id(app_id="my_hubspot_app_id)
```
