### ISSUE TITLE
How to get deal's onwer_Id in deals 

### ISSUE THREAD

**Issue by kostastheocharoulis** [HubSpot/hubspot-api-python#212]
I am trying to  retrieve the owner's id from the deals table using the api_client.crm.deals.get_all() method in the hubspot-api-python library . 

However the owner's id is not in the list below 

{'archived': False,
  'archived_at': None,
  'associations': None,
  'created_at': datetime.datetime(2023, 1, 11, 9, 20, 53, 350000, tzinfo=tzutc()),
  'id': '6400099030',
  'properties': {'amount': '500',
                 'closedate': '2023-01-31T09:20:37.526Z',
                 'createdate': '2023-01-11T09:20:53.350Z',
                 'dealname': 'HUBSPOT CERTIFICATION TEST',
                 'dealstage': '128372722',
                 'hs_lastmodifieddate': '2023-01-11T09:20:57.847Z',
                 'hs_object_id': '6400099030',
                 'pipeline': '49466849'},
  'properties_with_history': None,
  'updated_at': datetime.datetime(2023, 1, 11, 9, 20, 57, 847000, tzinfo=tzutc())},

Besides the following link i have not found any related info :
https://community.hubspot.com/t5/APIs-Integrations/How-to-retrieve-an-owner-object-or-owner-id-property-of-a-deal/m-p/466605

Any help would be appreciated

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @kostastheocharoulis. Try to change your request with adding `properties` parameter. It should be looks like:
```python3
api_client.crm.deals.get_all(properties=["hs_created_by_user_id"])
```
But if you need extra properties, you should separate them with commas. I hope this information was useful to you.

**Comment by kostastheocharoulis** [comment]
Thanks @alzheltkovskiy-hubspot , for the quick reply!

To merge the deal information, I would need something like the following 
`api_client.crm.deals.get_all(properties=["hs_created_by_user_id","amount","dealname","dealstage","hs_lastmodifieddate"])`
 
I can see the labels in the [url  ](https://knowledge.hubspot.com/crm-deals/hubspots-default-deal-properties?_ga=2.113578628.2090959854.1655392269-583420909.1655392269)but is there any reference url related to the available variables names ?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @kostastheocharoulis. Yes sure you can get all properties name for `deals` use this example:
```python
api_client.crm.properties.core_api.get_all(object_type="deals", properties="name")
```
Or you can get all properties from you account.

**Comment by kostastheocharoulis** [comment]
Thanks again for the prompt response 

Since there was an error :
```
---------------------------------------------------------------------------
ApiTypeError                              Traceback (most recent call last)
<ipython-input-264-f8a9072d37cd> in <module>
----> 1 api_client.crm.properties.core_api.get_all(object_type="deals", properties="name")

~\anaconda3\envs\ariadne\lib\site-packages\hubspot\crm\properties\api\core_api.py in get_all(self, object_type, **kwargs)
    285         """
    286         kwargs["_return_http_data_only"] = True
--> 287         return self.get_all_with_http_info(object_type, **kwargs)  # noqa: E501
    288 
    289     def get_all_with_http_info(self, object_type, **kwargs):  # noqa: E501

~\anaconda3\envs\ariadne\lib\site-packages\hubspot\crm\properties\api\core_api.py in get_all_with_http_info(self, object_type, **kwargs)
    323         for key, val in six.iteritems(local_var_params["kwargs"]):
    324             if key not in all_params:
--> 325                 raise ApiTypeError("Got an unexpected keyword argument '%s'" " to method get_all" % key)
    326             local_var_params[key] = val
    327         del local_var_params["kwargs"]

ApiTypeError: Got an unexpected keyword argument 'properties' to method get_all

```

I got them from the following 

` pd.DataFrame([flatten_json((x)) for x in api_client.crm.properties.core_api.get_all(object_type="Deals").to_dict()['results']])['name']`

**Comment by alzheltkovskiy-hubspot** [comment]
@kostastheocharoulis for it works well. Perhaps your exception due to `anaconda`. Can i close this issue?

**Comment by kostastheocharoulis** [comment]
Thank you for your assistance! You may go ahead and close the ticket. I appreciate your prompt support and help
