### ISSUE TITLE
release 3.4.0 is missing hubspot.crm.extensions

### ISSUE THREAD

**Issue by funkhaus-phil** [HubSpot/hubspot-api-python#22]
when installing the release 3.4.0 via pip, from hubspot import HubSpot throws "ModuleNotFoundError: No module named 'hubspot.crm.extensions'"

i took a look into the installed python packages and figured the folder is actually missing

i downgraded to 3.3.0 until the missing package is coming with the pip install

**Comment by atanasiuk-hubspot** [comment]
Hi, @funkhaus-phil, thank you for the report, we will check this asap.

**Comment by benhoff** [comment]
Think you guys need an __init__.py file in hubspot.crm.extensions in order for the directory to get picked up as a python module.

Installing fresh from the github repo causes me the same issue

**Comment by ksvirkou-hubspot** [comment]
Hi everyone 
check this version please [3.4.2](https://github.com/HubSpot/hubspot-api-python/tree/v3.4.2)
thanks everyone  for reporting this issue
