### ISSUE TITLE
SSL Handshake failure

### ISSUE THREAD

**Issue by zameji** [HubSpot/hubspot-api-python#221]
While running our ETL, we are getting random SSL handshake failures like this:
```
HTTPSConnectionPool(host='api.hubapi.com', port=443): Max retries exceeded with url: /crm/v3/objects/calls?limit=100&properties=hs_call_title&properties=hs_call_duration&properties=hs_call_status&properties=hs_timestamp&properties=hs_call_from_number&properties=hs_call_body&properties=hs_call_to_number&properties=hs_activity_type&associations=contacts&associations=companies&associations=deals&after=32852742180 (Caused by SSLError(SSLError(1, '[SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:1129)')))
<class 'requests.exceptions.SSLError'>
```

Unfortunately, we can't reproduce this reliably. The same code (hubspot-api-python v8.0.0) sometimes runs through, sometimes fails. The code is run via Github Action runner, we're not observing connection issues in any of our other workflows.

We updated our dependencies (in particular urrlib3 is now at 1.26.16) without seeing an improvement.

Is there anything we can do to narrow this down?

**Comment by zameji** [comment]
There is an open discussion for this issue on the [hubspot community forum](https://community.hubspot.com/t5/APIs-Integrations/SSL-v3-Handshake-Failure/m-p/811775/highlight/true#M65200). 

This does not seem to be an issue with the python library, but with HubSpot itself. Right now, though, HubSpot is trying to persuade us that we (the customers) are at fault here for "DDoSing" their API, even if we follow their rate limit specification.

Since the devs did not even acknowledge the issue here, I will close it. Please, join the discussion at the forum to track the development @cbeauch

**Comment by rondanen** [comment]
If you have this issue when running a library on Mac, such as Hubspot 8.0.0, sometimes, certain Python installations (especially on MacOS) do not install a set of default root certificates. You need to (re-)install certificates using the "Install Certificates.command" file in your Python install directory (usually **`/Applications/Python 3.x/`**).

You can run the "Install Certificates.command" file with superuser permissions using the **`sudo`** command in the terminal. Here's how you do it:

1. Open Terminal.
2. Change to the directory containing the "Install Certificates.command" file. For Python 3.8, the command would look something like this:
    
    ```bash
    cd /Applications/Python\ 3.8/
    ```
    
3. Run the "Install Certificates.command" file with **`sudo`**:
    
    ```bash
    sudo ./Install\ Certificates.command
    ```

**Comment by bsinni** [comment]
@zameji  thank you! I was looking at this for days

**Comment by lborruto** [comment]
> If you have this issue when running a library on Mac, such as Hubspot 8.0.0, sometimes, certain Python installations (especially on MacOS) do not install a set of default root certificates. You need to (re-)install certificates using the "Install Certificates.command" file in your Python install directory (usually **`/Applications/Python 3.x/`**).
> 
> You can run the "Install Certificates.command" file with superuser permissions using the **`sudo`** command in the terminal. Here's how you do it:
> 
> 1. Open Terminal.
> 2. Change to the directory containing the "Install Certificates.command" file. For Python 3.8, the command would look something like this:
>    ```shell
>    cd /Applications/Python\ 3.8/
>    ```
> 3. Run the "Install Certificates.command" file with **`sudo`**:
>    ```shell
>    sudo ./Install\ Certificates.command
>    ```

Here’s an enhanced version of your text:

Hi,
Thank you for your help! 
Everything is working perfectly on my computer, but I’m experiencing issues when I run my script in Azure (runbook).
Do you have any workarounds for this? I’ve tried several approaches, including using the Certifi package and uploading the certificate directly to Azure, but unfortunately, none of these solutions have worked.
