### ISSUE TITLE
Limit the amount of HubSpot.crm.companies.get_all()

### ISSUE THREAD

**Issue by Steenbuck** [HubSpot/hubspot-api-python#223]
Hey, 
I am developing an ETL process with your nice package which is wonderful but I'm missing a limit parameter in the get_all() method (at least for companies and contacts).  When devolping I don't want to query all result each time I run the debugger... Since I am devoloping with my companies data, this can take a while.  
The current limit parameter only limits the amount on each page but since the get_all method iterates over all pages this doesnt have any effect.

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @Steenbuck. We going to rework this method to make it suitable for such tasks. I will notify you when this happens.

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @Steenbuck. Could you check [the latest version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v11.0.0)?
