### ISSUE TITLE
Translating OpenAPI endpoints into client library methods

### ISSUE THREAD

**Issue by nrwhittle-beauhurst** [HubSpot/hubspot-api-python#224]
I'm having a bit of trouble trying to find the appropriate methods to call based on their OpenAPI endpoints, and was wondering if there's a way to translate between the two.

For example, if I wanted to know the appropriate method in this library to call `/marketing/v3/marketing-events/attendance/{externalEventId}/{subscriberState}/create` how am I supposed to know that's from this file: https://github.com/HubSpot/hubspot-api-python/blob/43bbdc18515e18c21a532660d6e7e1638299983a/hubspot/marketing/events/api/attendance_subscriber_state_changes_api.py#L170 ?

I found that by searching for the endpoint in this repo, but that doesn't feel like a sustainable way.

Is there perhaps a naming convention that I'm not seeing? Or a translation document?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @nrwhittle-beauhurst. Here is the [documentation](https://developers.hubspot.com/docs/api/marketing/marketing-events) that relates to `Marketing events` in which is collect the necessary endpoints . Unfortunately, there is no document where a list would be indicated to which endpoint which API relates.
