### ISSUE TITLE
Disappearance of associations_api method from crm.deals

### ISSUE THREAD

**Issue by noreallyimfine** [HubSpot/hubspot-api-python#225]
I've been using a script that leverages the function `client.crm.deals.associations_api.get_all()`.  I used this script as recently as July 7.

However yesterday when I ran the script, I got the following error:

`AttributeError: 'Discovery' object has no attribute 'associations_api'`

Did something change with the python client in the past few days that I missed?

Edit: I have a coworker that uses the JS client and said they have not experienced the same issue.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @noreallyimfine. Since [version](https://github.com/HubSpot/hubspot-api-python/tree/v8.0.0-beta.1) to access associations you need to use the changed syntax according to the [documentation](https://developers.hubspot.com/docs/api/crm/associations). I hope this information will be useful to you.

**Comment by frankV** [comment]
In case someone finds this thread later looking for a code example:

```python
client.crm.associations.v4.basic_api.create(
	object_type='contact',
	object_id=contact.id,
	to_object_type='company',
	to_object_id=company.id,
	association_spec=[{"associationCategory": "HUBSPOT_DEFINED", "associationTypeId": 1}]
)
        ```
