### ISSUE TITLE
While running sample app (contacts-app) on AWS ec2 (ubuntu), I am getting an error in  3rd line of Dockerfile.

### ISSUE THREAD

**Issue by malikdaman24** [HubSpot/hubspot-api-python#23]
ERROR: Service 'web' failed to build: ADD failed: stat /var/lib/docker/tmp/docker-builder941407767/hubspot: no such file or directory 
Require your help as why I am getting this?

**Comment by atanasiuk-hubspot** [comment]
Hi, @malikdaman24! Could you please provide more details on how you run the application and from which folder?
