### ISSUE TITLE
SSL certification Error 

### ISSUE THREAD

**Issue by pruthvirajksuresh** [HubSpot/hubspot-api-python#231]
```
from hubspot import HubSpot
api_client = HubSpot(access_token='pat-na1-xxxxxxxxxxxxxxxx')
from hubspot.crm.contacts import SimplePublicObjectInput
from hubspot.crm.contacts.exceptions import ApiException

try:
    simple_public_object_input = SimplePublicObjectInput(
        properties={"email": "test1@google.com"
                   }
    )
    api_response = api_client.crm.contacts.basic_api.create(
        simple_public_object_input=simple_public_object_input
    )
except ApiException as e:
    print("Exception when creating contact: %s\n" % e)

```

the above code resulting in the following error 

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.hubapi.com', port=443): Max retries exceeded with url: /crm/v3/objects/contacts?limit=100 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)')))

any help would be appricated

**Comment by miketsmith91** [comment]
Just encountered this after upgrading to the latest release. Check the scopes for the access token you are using in your hubspot org's setup and make sure you include the OAuth scope. Adding that scope fixed the issue for me.

**Comment by miketsmith91** [comment]
@pruthvirajksuresh Not a great solution but I downgraded to version 7.5.0 to sidestep the issue.

**Comment by kjschiroo** [comment]
We're also seeing this same issue. Is there anyway we can provide additional information to help resolve it?

**Comment by kjschiroo** [comment]
We were able to get around it by following the advice here: https://github.com/HubSpot/hubspot-api-python/issues/221#issuecomment-1644283915

However it seems like there may be a path that would not involve this sort of fiddling since we were able to succesfully run  `requests.get("https://api.hubspot.com")` without an SSL error on the same machine prior to installing the certificates.

**Comment by matthewkrausse** [comment]
`pip install pip_system_certs` worked for me

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @pruthvirajksuresh. It looks like this is a local problem related to certificates. You should install or update your certificates. To make sure the problem is not related to `HubSpot` you can check the server certificate `curl -v https://api.hubapi.com`
