### ISSUE TITLE
Setting configuration proxy of the api_client is not working

### ISSUE THREAD

**Issue by doregex** [HubSpot/hubspot-api-python#241]
I tried to configure the proxy before making an API request but it seems that is ignored.

My code is the following:
```
contacts_api = self.client.crm.contacts.basic_api
contacts_api.api_client.configuration.proxy = 'http://xyz'

contacts_api.get_page(
    after=after,
    limit=100,
    properties=contact_properties
)
```

Is there something I am missing?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @doregex. Since [version 11](https://github.com/HubSpot/hubspot-api-python/releases/tag/v11.0.0), we have added the ability to change all configuration parameters.
