### ISSUE TITLE
GET /settings/v3/users/ response is different (superadmin missing)

### ISSUE THREAD

**Issue by mfeyx** [HubSpot/hubspot-api-python#246]
hubspot-api-client==8.1.1
python=3.10

Based on the documentation I try to get the user information from the `/settings/v3/users/` endpoint. 
https://developers.hubspot.com/docs/api/settings/user-provisioning

### This is the python code documented

```python
import hubspot
from pprint import pprint
from hubspot.settings.users import ApiException

client = hubspot.Client.create(access_token="YOUR_ACCESS_TOKEN")

try:
    api_response = client.settings.users.users_api.get_page()
    pprint(api_response)
except ApiException as e:
    print("Exception when calling users_api->get_page: %s\n" % e)
```

### This is the result documented

```json
{
  "paging": {
    "next": {
      "link": "string",
      "after": "string"
    }
  },
  "results": [
    {
      "id": "123",
      "email": "newUser@email.com",
      "roleId": "100",
      "primaryTeamId": "101",
      "secondaryTeamIds": [
        "102"
      ],
      "superAdmin": "false"
    }
  ]
}
```

### This is the response I get when I make the call with the python package

```text
{'results': [{'id': '123',
              'name': 'Some Name',
              'secondary_user_ids': [],
              'user_ids': []}, ...
}
```

The `superAdmin` property is missing as you can see. I already tried to mimic other functions by adding the "properties" argument to the function, but that did not solve the problem.

However, if I make a regular GET request using curl or the python built-in module `urllib` I get the field.

Greetings

**Comment by mfeyx** [comment]
I digged a little bit deeper, and found the following [here](https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/settings/users/models/public_user.py)

``` python
# hubspot/settings/users/models/public_user.py
class PublicUser(object):

    openapi_types = {"id": "str", "email": "str", "role_id": "str", "primary_team_id": "str", "secondary_team_ids": "list[str]"}

    attribute_map = {"id": "id", "email": "email", "role_id": "roleId", "primary_team_id": "primaryTeamId", "secondary_team_ids": "secondaryTeamIds"}

    def __init__(self, id=None, email=None, role_id=None, primary_team_id=None, secondary_team_ids=None, local_vars_configuration=None): 
        ...
    )
    ...
```

The attribute is missing in Line 38 and 40. I tested it and added a `superAdmin` attribute and could retrieve the result.

What is the best way to add this to the repo? How can I contribute?

Greetings

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @mfeyx. The `superAdmin` parameter was added starting from [version 8.2.1](https://github.com/HubSpot/hubspot-api-python/releases/tag/v.8.2.1). For a better way to contribute, you can create an issue and tag me.
