### ISSUE TITLE
V3 signatures are valid for 50 minutes

### ISSUE THREAD

**Issue by omerfarukabaci** [HubSpot/hubspot-api-python#247]
As far as I can see, `MAX_ALLOWED_TIMESTAMP` attribute of `Signature` class should be set to `300`, which is 5 minutes as it is stated in the following announcement:

https://developers.hubspot.com/changelog/introducing-version-3-of-webhook-signatures

but currently it is set to `3000`, which is 50 minutes:

https://github.com/HubSpot/hubspot-api-python/blob/master/hubspot/utils/signature.py#L11

**Comment by alzheltkovskiy-hubspot** [comment]
@omerfarukabaci Thanks for bringing this issue to our attention. We are going to fix it as soon as possible.

**Comment by omerfarukabaci** [comment]
@alzheltkovskiy-hubspot Thank you! 🚀
