### ISSUE TITLE
Custom properties limit:  client.crm.deals.basic_api.get_page 

### ISSUE THREAD

**Issue by belbatera** [HubSpot/hubspot-api-python#248]
client.crm.deals.basic_api.get_page custom property limit

Hello.
I am developing a batch update process and I need to capture all records with their respective records in their custom property. Using the client.crm.deals.basic_api.get_page method, browsing all pages returns all 5000 records, but only returns 100 records with custom properties, even adding the property in the get_page method parameters.

```python
deals = []

next_page = 1
whileTrue:
     time.sleep(0.5)
     if next_page == 1:
         api_response = client.crm.deals.basic_api.get_page(limit=100, archived=False, properties=["jornada_etapa", "cod", "dias_da_primeira_compra", "dias_entre_as_compras", "pipeline"])
         for item in api_response.results:
             deals.append(item)
             next_page = api_response.paging.next.after
     else:
         api_response = client.crm.deals.basic_api.get_page(limit=100, archived=False, after=next_page)
         if len(api_response.results) > 0:
             for item in api_response.results:
                 deals.append(item)
             try:
                 next_page = api_response.paging.next.after
                 api_response.paging.next.link
             except AttributeError:
                 break
```

**Comment by alzheltkovskiy-hubspot** [comment]
Hello @belbatera. All objects have a method called `get_all` where you can retrieve all records of the needed object. Here the example:
```python
api_response = client.crm.deals.get_all(archived=False, properties=["jornada_etapa", "cod", "dias_da_primeira_compra", "dias_entre_as_compras", "pipeline"])
```
If I understand your problem correctly, you are getting 100 records with the required properties and all the rest without them. This may be because in the else block, you didn't set the properties. Please check that part.

**Comment by belbatera** [comment]
Obrigado @alzheltkovskiy-hubspot !
Funcionou.
