### ISSUE TITLE
discovery_base.py uses pkg_resources which is deprecated

### ISSUE THREAD

**Issue by ericbn** [HubSpot/hubspot-api-python#256]
Hi 👋

discovery_base.py uses pkg_resources from setuptools, which is deprecated (see [setuptools.pypa.io/en/latest/pkg_resources.html](https://setuptools.pypa.io/en/latest/pkg_resources.html)). Also, setuptools is not installed by default with Python 3.12.

Maybe it can be simplified to not rely on pkg_resources.

**Comment by davidve0206** [comment]
Hey, any ideas on how to fix this temporarily while HubSpot merges? I keep getting this error when I upload my app to kubernetes.

**Comment by ericbn** [comment]
@davidve0206, the workaround is to `pip install setuptools`.

**Comment by alzheltkovskiy-hubspot** [comment]
Hey everyone! Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v.10.0.0)?

**Comment by ericbn** [comment]
Issue solved with version 10.0.0. Thank you.
