### ISSUE TITLE
Support for CRM extensions accounting, specifically invoices

### ISSUE THREAD

**Issue by Bartman0** [HubSpot/hubspot-api-python#262]
From what I read in the API docs and the Hubsport Developer community, the CRM extensions API including support for invoices is non-existing anymore?
The old API had this support, but the migration guide switching to v3 of the API does not mention accounting nor invoices.

I checked the Python source code and the node.js API implementation. The latter has some support (getting invoices by id) but not a get_all() or something similar.

My question: are my findings correct? or am I looking in the wrong places?
if so, I could use some hints.    ;-)
And if you have some sample code that reads invoice data, I also would appreciate that.

What I would like to achieve:
- read (updated) invoice data from my HubSpot account
- forward these results to Twinfield to have them updated there

I also checked the webhooks support, but that doesn't have subscriptions on invoices either.

I would rather have asked this question on the Slack Hubspot developers channels, but the page where you can apply is corrupt.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @Bartman0. Support for Accounting Client will be discontinued in the next versions of the SDK.
