### ISSUE TITLE
v3 signature does not match when validating via `Signature.is_valid()`

### ISSUE THREAD

**Issue by Teraskull** [HubSpot/hubspot-api-python#263]
The timestamp parameter in `is_valid()` accepts a `float`:

https://github.com/HubSpot/hubspot-api-python/blob/db17b98c9f099c337c4200b97ebc2370a76e88e8/hubspot/utils/signature.py#L21

However, if we get the timestamp from the header, and use the float value in `is_valid()`:
```python
timestamp = request.headers.get("x-hubspot-request-timestamp")

Signature.is_valid(..., float(timestamp))

```

We will get a hash mismatch because in `get_signature()`, timestamp is also a `float`:

https://github.com/HubSpot/hubspot-api-python/blob/db17b98c9f099c337c4200b97ebc2370a76e88e8/hubspot/utils/signature.py#L45

The mismatch happens because of, for example, converting `1707926838792` to `float`, and now the `source_string` contains `1707926838792.0`:

https://github.com/HubSpot/hubspot-api-python/blob/db17b98c9f099c337c4200b97ebc2370a76e88e8/hubspot/utils/signature.py#L53-L54

A suggestion would be to instead allow the timestamp to be `str` in both `is_valid()` and `get_signature()`, and convert the timestamp to `float` when comparing to the `current_time`.

## Fix:

Here is the whole `signature.py` diff that fixes this issue.

This also fixes #247 since the timestamps are now handled as seconds and not milliseconds.

I also changed the hash comparison to use `hmac.compare_digest()` to prevent timing attacks.

```diff
import base64
import hmac
import hashlib

-from datetime import datetime
+from datetime import datetime, UTC, timedelta

from hubspot.exceptions import InvalidSignatureVersionError, InvalidSignatureTimestampError


class Signature:
-	MAX_ALLOWED_TIMESTAMP = 3000
+	MAX_ALLOWED_TIMESTAMP = 300

+	@staticmethod
+	def _is_timestamp_valid(timestamp: str) -> bool:
+		if timestamp is None:
+			return False
+		try:
+			timestamp_float = float(timestamp)
+			request_time = datetime.fromtimestamp(timestamp_float // 1000, tz=UTC)
+			current_time = datetime.now(UTC)
+			return current_time - request_time < timedelta(seconds=Signature.MAX_ALLOWED_TIMESTAMP)
+		except (ValueError, OverflowError):
+			return False

    @staticmethod
    def is_valid(
        signature: str,
        client_secret: str,
        request_body: str,
        http_uri: str = None,
        http_method: str = "POST",
        signature_version: str = "v2",
-		timestamp: float = None
+		timestamp: str = None
    ) -> bool:
        if signature_version == "v3":
-			current_time = datetime.now()
-			if timestamp is None or current_time.timestamp() - timestamp > Signature.MAX_ALLOWED_TIMESTAMP:
+			if timestamp is None or not Signature._is_timestamp_valid(timestamp):
                raise InvalidSignatureTimestampError(timestamp=timestamp)
        hashed_signature = Signature.get_signature(
            client_secret,
            request_body,
            signature_version,
            http_uri,
            http_method,
            timestamp
        )

-		return signature == hashed_signature
+		return hmac.compare_digest(hashed_signature, signature)

    @staticmethod
    def get_signature(
        client_secret: str,
        request_body: str,
        signature_version: str,
        http_uri: str = None,
        http_method: str = "POST",
-		timestamp: float = None,
+		timestamp: str = None
    ) -> str:
        if signature_version == "v1":
            source_string = f"{client_secret}{request_body}"
            return hashlib.sha256(source_string.encode("utf-8")).hexdigest()
        elif signature_version == "v2":
            source_string = f"{client_secret}{http_method}{http_uri}{request_body}"
            return hashlib.sha256(source_string.encode("utf-8")).hexdigest()
        elif signature_version == "v3":
            source_string = f"{http_method}{http_uri}{request_body}{timestamp}"
            hashed_signature = base64.b64encode(
                hmac.new(
                        client_secret.encode("utf-8"),
                        msg=source_string.encode("utf-8"),
                        digestmod=hashlib.sha256
                        ).digest()
            ).decode()
            return hashed_signature
        else:
            raise InvalidSignatureVersionError(signature_version=signature_version)
```

Please let me know if I'm missing something, but I was not able to successfully use `Signature.is_valid()` without these changes, since it always returned `False`. Thanks!

**Comment by Teraskull** [comment]
@alzheltkovskiy-hubspot can you please verify that the v3 validation fails?

**Comment by andobolocco** [comment]
any update here ? I have the same problem, this is pressing, we need to validate our webhook requests are coming from hubspot!

**Comment by andobolocco** [comment]
also this README is wrong, we should not be using `datetime.now().timestamp` here, but the timestamp provided by the `X-Hubspot-Request-Timestamp` header, right?
![image](https://github.com/HubSpot/hubspot-api-python/assets/842842/02c17f35-b7f7-4692-a619-edeac3c53217)

**Comment by volcinschi** [comment]
Same issue here, although I can't seem to make a hash like the one sent in `X-HubSpot-Signature-v3` via `get_signature` patched in the proposed solution :/

**Comment by Teraskull** [comment]
@volcinschi Hm, can you give me an MRE with your use-case? I get the same hash using my proposed changes.

How are you getting the hash from the `x-hubspot-signature-v3` header?

Are all the required values (method, URL, response body and timestamp) of `str` type and without leading/trailing spaces?

Make sure the URL protocol is `https` and the method is all-caps like `POST`.

Maybe the response body is `bytes` instead of `str`?

The `timestamp` should be in milliseconds and not seconds. You can get it from the `x-hubspot-request-timestamp` header.

Any deviation from these things will cause a hash mismatch.
Those are the main issues that can happen, from the top of my head.

**Comment by volcinschi** [comment]
I'm using python Serverless AWS Lambda through an AWS API Gateway and the body seems to be getting modified somehow since using parameters locally seems to work :/ 

The only disclaimer is that I had to use `timezone.utc` instead of `UTC` in the `datetime` code

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone. We are going to fix this in the new release. Thank you for bringing this to our attention.

**Comment by Teraskull** [comment]
@alzheltkovskiy-hubspot Tested version `10.0.0` and can confirm the `Signature.is_valid()` now works as expected, thanks!

One small thing, as @andobolocco mentioned, in the readme, `datetime.now().timestamp` can't be used for the timestamp, since it won't match the signature. Might be confusing when copying the example.

**Comment by alzheltkovskiy-hubspot** [comment]
@Teraskull Glad to hear it. I will fix the README as soon as I can. Can i close the issue?

**Comment by Teraskull** [comment]
@alzheltkovskiy-hubspot Thanks, sure!
