### ISSUE TITLE
Please mention proper redirect_uri to be configured in the Hubspot App for all the example sample app in their README.md files

### ISSUE THREAD

**Issue by mj-roychowdhury** [HubSpot/hubspot-api-python#27]
There were no mention how would we configure the redirect_uri for any app given in the sample-apps. I was trying with http://localhost:300. Many hubspot node examples have the pattern as http://localhost:3000/oauth-callback. 

But the sample apps firstly works with only port = 5000 as the docker file named web runs on 5000 according to the docker-compose.yml file.
Also, the redirect_uri in the app should be specifically "http://localhost:5000/oauth/callback" for this python module sample apps. Would be really helpful for the developers who is a starter like me both in Webapps and Hubspot if this information is mentioned in the README.md file

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @mj-roychowdhury 
Could you check [sample-app-oauth README](https://github.com/HubSpot/sample-apps-oauth/blob/main/python/README.md)?
This information should be helpful for you.
