### ISSUE TITLE
Example for creating a deal + trello example doesnt work

### ISSUE THREAD

**Issue by wadewilliams** [HubSpot/hubspot-api-python#28]
Looking for an example of creating a deal. While searching this repo I found this

https://github.com/HubSpot/hubspot-api-python/blob/master/sample-apps/trello-integration-app/src/routes/trello/webhooks.py#L29 

```
In [11]: hubspot.crm.deals.basic_api
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-16000a60ab80> in <module>
----> 1 hubspot.crm.deals.basic_api

AttributeError: module 'hubspot.crm.deals' has no attribute 'basic_api'
```

Seems like it should be `hubspot.crm.deals.api.basic_api`

**Comment by atanasiuk-hubspot** [comment]
Hi, @wadewilliams. Checked trello app, `hubspot.crm.deals.basic_api` seems to be the right usage. Could you maybe provide more details on how you're accessing deals api?

**Comment by wadewilliams** [comment]
Thanks @atanasiuk-hubspot 

I'm trying to use the deals API but I see no working example. Perhaps you could provide a simple example of how to create a deal or at least call the API. The trello sample was one of the few places that appear to doing anything with the deals API. 

To be clear I do not care about the trello sample. I merely am looking to create and update deals using the SDK and cannot find a working example.

```
In [1]: import hubspot

In [2]: hubspot.crm.deals.basic_api.get_by_id("anything")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-16000a60ab80> in <module>
----> 1 hubspot.crm.deals.basic_api

AttributeError: module 'hubspot.crm.deals' has no attribute 'basic_api'
```

**Comment by atanasiuk-hubspot** [comment]
> Perhaps you could provide a simple example of how to create a deal or at least call the API.

You should be able execute smth similar to:
```
from hubspot import HubSpot

client = HubSpot(api_key="<yourhapikey>")
deal = client.crm.deals.basic_api.get_by_id("anything")
print(deal)
```

**Comment by wadewilliams** [comment]
Ahh. Thank you for that. The naming of the client as `hubspot` apparently threw me off.
