### ISSUE TITLE
API Documentation appears incorrect for "get_by_name" and client.crm.lists.memberships_api.get_page

### ISSUE THREAD

**Issue by robrice** [HubSpot/hubspot-api-python#298]
The python documentation uses:
client.crm.lists.list_app_api.get_by_name

But the correct function call 
client.crm.lists.lists_api.get_by_name

In https://developers.hubspot.com/docs/api/crm/lists

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @robrice. Could you check the latests [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v9.0.0)?
