### ISSUE TITLE
Get All not getting all properties

### ISSUE THREAD

**Issue by RWiggers** [HubSpot/hubspot-api-python#3]
Hi everyone,

I'm getting all my contacts from Hubspot, but when I look into the properties, there is only basic properties and values. My custom properties, properties that I have created, is not in the object.

Someone knows how to get custom properties as well?

Thanks.
Rodrigo.

**Comment by atanasiuk-hubspot** [comment]
Hi, @RWiggers 

You have to manually specify a list of properties you want to receive:
```python
api_response = client.crm.contacts.get_all(properties=["firstname", "lastname", "email", "address"])
```

Otherwise only default ones are in the response.

**Comment by RWiggers** [comment]
Thanks @atanasiuk-hubspot,

Is there any way to make it dynamically? I mean, if any property has any value, return it in the request response?

Otherwise I need to map all the properties that an object has e make a requests with them.

Thanks in advance.

**Comment by atanasiuk-hubspot** [comment]
At this moment, unfortunately, no. Until it is implemented on API side

**Comment by yfaktor** [comment]
> At this moment, unfortunately, no. Until it is implemented on API side

@RWiggers - to add to it - our backend team does have this on their TODO list , so stay tuned. Once it is available in the API we will update the SDKs

**Comment by RWiggers** [comment]
> > At this moment, unfortunately, no. Until it is implemented on API side
> 
> @RWiggers - to add to it - our backend team does have this on their TODO list , so stay tuned. Once it is available in the API we will update the SDKs

Good news! I'll be waiting for this.

Thank you!
Rodrigo.
