### ISSUE TITLE
I am not able to call this API: client.crm.lists.lists_api.do_search

### ISSUE THREAD

**Issue by Hariomsimform** [HubSpot/hubspot-api-python#304]
Error: 'Discovery' object has no attribute 'lists_api'

def get_hubspot_lists(access_token, params):
    client = hubspot.Client.create(access_token=access_token)
    
    try:
        # Retrieve all lists
        list_search_request = ListSearchRequest(
            offset=0,
            count=0,
            additional_properties=["string"]
        )
        response = client.crm.lists.lists_api.do_search(
            list_search_request=list_search_request
        )
        headers = {
            'Authorization': f'Bearer {access_token}',
            'Content-Type': 'application/json'
        }
        output = {
            "companies": [],
            "contacts": []
        }
        
        for lists in response.results:
            if lists.object_type_id == "0-1":
                object_type = "contacts"
            else:
                object_type = "companies"
                
            url = f"https://api.hubapi.com/crm/v3/lists/{lists.id}/memberships"
            response = requests.get(url, params=params, headers=headers)
            response_data = response.json()
            
            if response_data.get("results"):
                record = [record["recordId"] for record in response_data["results"]]
                if object_type == 'companies':
                    output["companies"].extend(record)
                elif object_type == 'contacts':
                    output["contacts"].extend(record)
        return output
    
    except Exception as e:
        # Handle exceptions
        print(f"Error: {e}")
        return None

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @Hariomsimform. In the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v9.0.0) of SDK the name `lists_api` was changed to `list_app_api`.
