### ISSUE TITLE
'Discovery' object has no attribute 'basic_api'

### ISSUE THREAD

**Issue by data-bloomwell** [HubSpot/hubspot-api-python#312]
Hi Everyone,
with the v4 api, I'm trying to get the associations, I just upgraded hubspot api from 7.0.0 to 9.0.0, but its the same code which runs well on the documentation website but doesn't work when I run it on my laptop.
I've the following environment
IDE: JupyterNotebook
Python Version: 3.11.3
hubspot-api-client: 9.0.0

script is as follow

```
try:
    api_response = client.crm.associations.v4.basic_api.get_page(object_type="contact", object_id="4115", to_object_type="2-118112", limit=10)
    pprint(api_response)
except ApiException as e:
    print("Exception when calling basic_api->get_page: %s\n" % e)
```
    
   the error message:
   AttributeError: 'Discovery' object has no attribute 'basic_api'
   
   
  
   when I check dir with `dir(client.crm.associations)` i get the following
   
   ['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_configure_api_client',
 '_default_api_factory',
 'batch_api',
 'config',
 'types_api',
 'v4']

**Comment by turtle3791** [comment]
I am getting the same when running the code from colab or command line.
     68         while True:
     69             try:
---> 70                 associations = client.crm.associations.v4.associations_api.get_all(
     71                     from_object_type='companies',
     72                     from_object_id=company_id,

AttributeError: 'Discovery' object has no attribute 'associations_api'

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @turtle3791. You tried to call a non-existent API `associations_api` and method `get_all`, which resulted in the corresponding error. More information how use the Client you can find [here](https://developers.hubspot.com/beta-docs/reference/api/crm/associations/association-details#basic).

**Comment by alzheltkovskiy-hubspot** [comment]
@data-bloomwell. I have used the same request `client.crm.associations.v4.basic_api.get_page(object_type="contact", object_id="object_id", to_object_type="companies", limit=10)` and for me it works well. Try using another IDE and if the problem persists please let me know.
