### ISSUE TITLE
How to get emails of marketing section

### ISSUE THREAD

**Issue by nghiahsgs** [HubSpot/hubspot-api-python#315]
Hi team

I am try to get emails of marketing section
I try this code
```python
try:
    # Access the marketing emails API
    email_campaigns = api_client.marketing.emails.get_page(limit=10)
    for email in email_campaigns.results:
        print(f"Email ID: {email.id}, Subject: {email.subject}, Status: {email.status}")
except ApiException as e:
    print("Exception when calling HubSpot API: %s\n" % e)
  ```
  
  but it didn't work
  
  it got error
  ```
  Traceback (most recent call last):
  File "/Users/lypk/backoffice-services/hubspot-pylib/test.py", line 33, in <module>
    email_campaigns = api_client.marketing.emails.get_page(limit=10)
AttributeError: 'Discovery' object has no attribute 'emails'
  ```

**Comment by nghiahsgs** [comment]
<img width="482" alt="image" src="https://github.com/user-attachments/assets/9606ae81-08c1-4600-bea7-e8d293c391fe">

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @nghiahsgs. The functionality you're interested in is currently in [beta](https://developers.hubspot.com/docs/api/marketing/marketing-email), so it hasn't been added to the SDK yet, but we plan to include it in one of the upcoming versions.

**Comment by nghiahsgs** [comment]
Yes, thank for you information @alzheltkovskiy-hubspot !
