### ISSUE TITLE
DeprecationWarning: pkg_resources

### ISSUE THREAD

**Issue by ALeksandr-Fuze** [HubSpot/hubspot-api-python#316]
Python = "3.12"
hubspot-api-client = "9.0.0"

**Deprecation warning:**
hubspot\discovery\discovery_base.py:1: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @ALeksandr-Fuze ! Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v.10.0.0)?
