### ISSUE TITLE
hubspot-api-client library size

### ISSUE THREAD

**Issue by matthieudesprez** [HubSpot/hubspot-api-python#317]
We are using the HubSpot API client on AWS Lambda, and noticed that it is consuming a significant amount of disk space.   

Is there a way to optimize the disk space usage or are there alternative solutions that can be explored to reduce it ? Like splitting it into different modules ? We're only using the crm part.

Thank you

```
$ du -sh ./hubspot/* | sort -h
4.0K	./hubspot/__init__.py
4.0K	./hubspot/client.py
4.0K	./hubspot/exceptions.py
4.0K	./hubspot/hubspot.py
 12K	./hubspot/utils
116K	./hubspot/conversations
156K	./hubspot/auth
188K	./hubspot/communication_preferences
264K	./hubspot/events
268K	./hubspot/discovery
268K	./hubspot/webhooks
344K	./hubspot/settings
408K	./hubspot/files
436K	./hubspot/automation
1.4M	./hubspot/marketing
3.7M	./hubspot/cms
 12M	./hubspot/crm
```

**Comment by alzheltkovskiy-hubspot** [comment]
Hey all. Now clients are generated automatically, it inevitably leads to the duplication of many files and, consequently, an increase in disk space usage, which is beyond our control. Currently, we are working on a new SDK version that should address this issue. However, this is not a quick process and may take a significant amount of time.
