### ISSUE TITLE
TIcket Merge Bug

### ISSUE THREAD

**Issue by javfenchel** [HubSpot/hubspot-api-python#319]
According to the API reference tickets is supposed to have a public_object_api property, but whenever I tried to call that property (to merge tickets) it gave me the error
AttributeError: 'Discovery' object has no attribute 'public_object_api'

After looking through the source code I found that in the file hubspot/discovery/crm/tickets/discovery.py it's missing some lines that existed in the equivalent company file (hubspot/discovery/crm/companies/discovery.py). I copied these lines into the ticket file on my local machine and it now works. 

    @property
    def public_object_api(self) -> api_client.PublicObjectApi:
        return self._configure_api_client(api_client, "PublicObjectApi")

I also use python code in workflow custom code and would like to see this update pushed there so I can merge tickets in workflows (without having to switch languages or use requests).

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @alzheltkovskiy-hubspot. You are absolutely right, the client does not fully align with the documentation. We will correct this in the next version. Thank you for pointing out the inaccuracy.
