### ISSUE TITLE
Help needed - Is there any way to load all the events using Web Analytics API

### ISSUE THREAD

**Issue by maheshsonavane** [HubSpot/hubspot-api-python#33]
The Web Analytics endpoint allows developers to find and filter events associated with a CRM object of any type. Do we have any way to get all the events exported?

URL: https://developers.hubspot.com/docs/api/events/web-analytics

**Comment by atanasiuk-hubspot** [comment]
Hi, @maheshsonavane, Web Analytics client is coming soon to SDK

**Comment by alainjabmo** [comment]
Any news here ??

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone
This APP was added since [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v3.7.2)
Thank you.

**Comment by adrianrfreedman** [comment]
Hi,

Thanks for your response but you haven't answered OP's question.

From the link that was posted, it doesn't specify if it's possible to perform a general export of all events of all types. Is this possible, and if so, what does such a query look like?

Thanks in advance.
