### ISSUE TITLE
EVENTS API - Sort parameter is returning error message - Not consistent with API documentation

### ISSUE THREAD

**Issue by rginsberg549** [HubSpot/hubspot-api-python#333]
https://github.com/HubSpot/hubspot-api-python/blob/5e0e06a11aa436af0b3c1ef11e4d97a53d0984ed/hubspot/events/api/events_api.py#L65

Please help me understand the following error.  The use case is to return the most recent event from a company.  I want a single event (limit=1) but the most recent (sort=["descending"]) for a specific Company and Event Type.

`HTTP response body: {"status":"error","message":"Only a single sort field 'occurredAt' is supported","correlationId":"e958ed2f-a777-4bc1-b1cd-c0d33046c6d5","category":"VALIDATION_ERROR"}`

Here is my code for reference.

```
`
import hubspot
from pprint import pprint
from hubspot.events import ApiException

client = hubspot.Client.create(access_token="")

try:
    api_response = client.events.events_api.get_page(limit=1, 
                                                     object_type="company", 
                                                     event_type="{EVENT TYPE}", 
                                                     object_id="{COMPANY OBJECT ID}",
                                                     sort=["DESCENDING"])
    pprint(api_response)
except ApiException as e:
    print("Exception when calling events_api->get_page: %s\n" % e)`
```
    
    
   I am following the documentation listed here --> https://developers.hubspot.com/beta-docs/reference/api/analytics-and-events/event-analytics#get-%2Fevents%2Fv3%2Fevents%2F

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @rginsberg549. Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v.10.0.0)?
