### ISSUE TITLE
hubspot.utils.signature is broken for python < 3.11

### ISSUE THREAD

**Issue by jekru** [HubSpot/hubspot-api-python#361]
```python
import base64
import hmac
import hashlib

from datetime import datetime, UTC, timedelta # <--- datetime.UTC is not available for python < 3.11
```
_hubspot/utils/signature.py_

---

- `datetime.UTC` (alias for `datetime.timezone.utc`) is available since python 3.11, see [What’s New In Python 3.11](https://docs.python.org/3/whatsnew/3.11.html#datetime). For older versions, this will raise an `ImportError`.
- Changed in commit [f31fa724a3fa28a322c45681d318b8a1030f943d](https://github.com/HubSpot/hubspot-api-python/commit/f31fa724a3fa28a322c45681d318b8a1030f943d#diff-b4965eed11e18801b94b58883140dd3c5c9cdd894b88ccf03ff7aaa314db8a84R5).
- Related to #263.

**Possible solution**: Use `timezone.utc`.

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @jekru. Thank you for your participation. We will try to fix it in the next version.

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @jekru. Could you check [the latest version](https://github.com/HubSpot/hubspot-api-python/releases/tag/11.1.0)?
