### ISSUE TITLE
Breaking changes on get_all with limit param

### ISSUE THREAD

**Issue by Bregzl** [HubSpot/hubspot-api-python#364]
I noticed that you updated the fetch_all method in this [commit](https://github.com/HubSpot/hubspot-api-python/commit/3f71b6a7e1abf08eb7d3e383d89b8a0cc48a22d0#diff-ec2413008c0d0fb98acfb27acf93ed143ad4386f4dfaa169711bf95edd74fea7R5).

However, there seems to be an issue with the way this method was changed.
Before the [v11 release](https://github.com/HubSpot/hubspot-api-python/releases/tag/v11.0.0), if the `get_all` method was used with the `limit` parameter to control the number of results per page, it worked as expected. But after v11, the `fetch_all` method no longer sets `PAGE_MAX_SIZE` as it used to. Instead, it applies the limit to the total result size.

This behavior causes the method to return only 100 rows in total, regardless of the pagination settings.

Suggestion: The parameter for limiting the total result size should be renamed to avoid confusion with the previous `limit` parameter, which was used for pagination.

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @Bregzl. As you correctly noted, the `limit` parameter previously worked like for request to `get_page`, which was not entirely correct because it did not make much sense for users, but now it works as expected.
