### ISSUE TITLE
urllib3 2.x compatibility dropped?

### ISSUE THREAD

**Issue by norrisjeremy** [HubSpot/hubspot-api-python#366]
The recent 11.0.0 release removed compatibility with urllib3 2.x in changeset 103ae7c without detailing any reason why it was dropped. Additionally, this was not called out in the 11.0.0 release notes.
Please consider restoring this compatibility so that users that have adopted urllib3 2.x can continue to use the hubspot-api-client library.

**Comment by yuekui** [comment]
I think [that](https://github.com/HubSpot/hubspot-api-python/issues/226)'s probably the reason

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @norrisjeremy. Thanks for this issue. We going to fix it soon.

**Comment by daabr** [comment]
@alzheltkovskiy-hubspot apparently this was already fixed in https://github.com/HubSpot/hubspot-api-python/commit/303ebf33a6f37f82aad613fd5c1fb62f00c4f889 - right after releasing 11.0.0.

Any chance you could tag a new release soon, so it'll take effect? This is causing a dependency conflict with another library that we're using.

Thanks!

**Comment by alzheltkovskiy-hubspot** [comment]
Hey all. Could you check [the latest version](https://github.com/HubSpot/hubspot-api-python/releases/tag/11.1.0)?

**Comment by daabr** [comment]
Confirming that with 11.1.0 we can install urllib3 v2.x. Thanks!

**Comment by ericbn** [comment]
Here are the recommendations for supporting **both urllib3 v1.26.x and v2.0**: https://urllib3.readthedocs.io/en/stable/v2-migration-guide.html#migrating-as-a-package-maintainer.

Also, it's unclear why `requests` was added as a dependency, when the code was already using urllib3 directly. This should have nothing to do with #226.

**Comment by alzheltkovskiy-hubspot** [comment]
@ericbn. `Request` was added as a dependency to enable the use of requests via `curl`, and information about this has been included in the `README`.
