### ISSUE TITLE
update objects, e.g. contacts?

### ISSUE THREAD

**Issue by mwenglein** [HubSpot/hubspot-api-python#41]
is there a way to first fetch, then update a contact, for example? or update directly if the contact's id is known?

**Comment by plaurynovich-hubspot** [comment]
Hi, @mwenglein. You can update a contact with
`hubspot.crm.contacts.basic_api.update(contact_id, simple_public_object_input=properties)`
or (and) fetch it with
`hubspot.crm.contacts.basic_api.get_by_id(contact_id)`
Please, check [contacts app sample](https://github.com/HubSpot/hubspot-api-python/tree/master/sample-apps/contacts-app) if you need more samples for contacts.
