### ISSUE TITLE
get_all response to dict

### ISSUE THREAD

**Issue by andiMenge** [HubSpot/hubspot-api-python#43]
Hey,
I'm new to the HS SDK and I'm wondering if I can get a python dict or JSON out of a `hsClient.crm.deals.get_all()` call instead of a `SimplePublicObject ` type. 🙏

**Comment by atanasiuk-hubspot** [comment]
Hi, @andiMenge 

You may find useful `to_dict` method:

```
contacts = client.crm.contacts.get_all()

for contact in contacts:
    print(contact.to_dict())
```

**Comment by rajojon23** [comment]
Thank you for this! I was scratching my head the whole day looking for a fix. Used it to get HS contacts based on ID. 
` contact_fetched = api_client.crm.contacts.basic_api.get_by_id(contact_id)
  temp = contact_fetched.to_dict()`
