### ISSUE TITLE
Batch retrieving V1 models and initializing V3 objects?

### ISSUE THREAD

**Issue by ghost** [HubSpot/hubspot-api-python#46]
How can I initialize V3 contact object models from the V1 API? (That's awesome that V1 will be supported but it seems the responses are incompatible with V3 responses.)

This doesn't seem to work or be the correct way to do it:
```python
    from hubspot.crm.contacts import SimplePublicObject, CollectionResponseSimplePublicObject

    url = "https://api.hubspot.com/contacts/v1/contact/emails/batch/"
    emails = list(map(lambda registrant: registrant.email, group_of_100_registrants))
    params = {
        "hapikey": settings.HUBSPOT_API_KEY,
        "formSubmissionMode": "none",
        "email": emails,
        "property": "my_custom_property_to_check_if_contact_needs_update",
    }
    response = requests.get(
        url, params=params, timeout=settings.HUBSPOT_REQUEST_TIMEOUT
    )
    contacts = CollectionResponseSimplePublicObject(response.json())
```

And even if there's only one contact in my response, this doesn't work either (it sets the `id` to a dictionary of properties):
```python
    contact = SimplePublicObject(response.json()['12345'])
```

**Why:** I need to retrieve a batch of contacts so I can determine which ones need to be updated via a custom field that is set by my external integration script each time it is run.

With the V3 API, I can only search on three filters at once, meaning going through a list of 3,000 contacts would cost 1,000 API calls.

With the V1 API (https://api.hubspot.com/contacts/v1/contact/emails/batch/), I can request 100 at a time, which is much more reasonable.

I can get the JSON back using Python requests just fine.

**But how do I get these into the V3 contact models so I can do something with them and then batch-update them through this newer V3 API ... if possible?***

**Comment by plaurynovich-hubspot** [comment]
Hi, @tgrushka. Probably, you should use v3 for both read and update. There is a "limit" option for v3 as well. Please, check it [here](https://developers.hubspot.com/docs/api/crm/contacts). Also, you can use BatchApi client.
