### ISSUE TITLE
Using get_all and a filter on contacts 

### ISSUE THREAD

**Issue by alfredo-vive** [HubSpot/hubspot-api-python#49]
Is there a way to use a filter such as 

```
   server_filter = Filter(
        property_name="server",
        operator="EQ",
        value=
    )
    public_object_search_request = PublicObjectSearchRequest(
        filter_groups=[filter_group],
        properties=properties,
    )
```
and do something like:

```
 contacts_result = hubspot_api.crm.contacts.search_api.do_search(
            public_object_search_request=public_object_search_request,
        ).get_all()

```
or 

`hubspot_api.crm.contacts.get_all(filter=server_filter)`

having 3k+ contacts makes it so that I sometimes trigger the `secondly limit` when using a while loop and the `after` param etc

**Comment by plaurynovich-hubspot** [comment]
Hello,

There is a way to use filter such as:

```
server_filter = Filter(
    property_name="server",
    operator="EQ",
    value=
)

filter_group = FilterGroup(
  filters=[server_filter]
)

public_object_search_request = PublicObjectSearchRequest(
  filter_groups=[filter_group]
)

hubspot_api = HubSpot(api_key=your_api_key)

contacts_result = hubspot_api.crm.contacts.search_api.do_search(
  public_object_search_request=public_object_search_request
)
```

**Comment by plaurynovich-hubspot** [comment]
Also, you can use

```
hubspot_api.crm.contacts.basic_api.get_page()
```

to get your contacts paginated.
I think it should be all of them or some of them filtered, not both.

**Comment by alfredo-vive** [comment]
> Hello,
> 
> There is a way to use filter such as:
> 
> ```
> server_filter = Filter(
>     property_name="server",
>     operator="EQ",
>     value=
> )
> 
> filter_group = FilterGroup(
>   filters=[server_filter]
> )
> 
> public_object_search_request = PublicObjectSearchRequest(
>   filter_groups=[filter_group]
> )
> 
> hubspot_api = HubSpot(api_key=your_api_key)
> 
> contacts_result = hubspot_api.crm.contacts.search_api.do_search(
>   public_object_search_request=public_object_search_request
> )
> ```

I'm aware you can do this, but it will only give you up to 100 max contacts (max value for `limit` in `PublicObjectSearchRequest`). Currently I'm doing this similar the the implementation of `get_all`:

```
contacts_results = []
    after = 0
    while True:
        public_object_search_request = PublicObjectSearchRequest(
            filter_groups=[filter_group],
            properties=properties,
            limit=100,
            after=after
        )
        contacts_result = hubspot_api.crm.contacts.search_api.do_search(
            public_object_search_request=public_object_search_request,
        )
        contacts_results.extend(contacts_result.results)
        if not contacts_result.paging:
            break
        after = contacts_result.paging.next.after

```

But if there are a lot of contacts I can reach the secondly limit.
