### ISSUE TITLE
Basic get_or_create contact + docs questions

### ISSUE THREAD

**Issue by wadewilliams** [HubSpot/hubspot-api-python#5]
Hello,

 Is this for production use?

 The API docs referrenced in the README refer to v1 but as I understand this sdk interacts with the v3 api

 The newer api docs available at https://developers.hubspot.com/docs/api all have raw python implementations as examples and do not use this sdk.

 Where is someone to start with building a modern hubspot integration right now?

**Comment by yfaktor** [comment]
Thanks for posting this @wadewilliams  - our README did go stale actually, we should fix it.
WRT using SDK in snippets it is indeed being actively worked on - it is coming soon.
Meanwhile, please take a look at the [sample-apps](https://github.com/HubSpot/hubspot-api-python/tree/master/sample-apps) folder to check out the examples of making API calls using SDKs

**Comment by wadewilliams** [comment]
Thanks for the quick reply.

State of repo? Is this production grade right now or should we use something else to build a modern python integration at the present time?

**Comment by wadewilliams** [comment]
The sample-apps are helpful but they assume a lot -- I'm simply trying to create/update a contact and it isn't abundantly clear how to do that since we are supporting a flask project in the sample-apps

**Comment by yfaktor** [comment]
> The sample-apps are helpful but they assume a lot -- I'm simply trying to create/update a contact and it isn't abundantly clear how to do that since we are supporting a flask project in the sample-apps
Got it, thank you for clarification. How about the code snippets in README - we are trying to cover the simplest cases there (though ultimate solution will be using SKDs in  code snippets in the. manual and it is coming) - there is this code for example

```
from hubspot.crm.contacts import ApiException

try:
    contact_fetched = client.crm.contacts.basic_api.get_by_id('contact_id')
except ApiException as e:
    print("Exception when requesting contact by id: %s\n" % e)

```
replacing get_by_id with create would do the trick there

**Comment by wadewilliams** [comment]
Thank you for this. 

 It appears that there is no method to `get_or_create` like there was with the older API? Any plans to add? 

 Working off the sample apps I came up with this minimal client with a `get_or_create` method:


```
from django.conf import settings
import hubspot
from hubspot.crm.contacts import (
    SimplePublicObject,
    PublicObjectSearchRequest,
    Filter,
    FilterGroup,
)


class HubspotClient:
    def __init__(self):
        self.client = hubspot.Client.create(api_key=settings.HUBSPOT_API_KEY)

    def get_or_create(self, email, props):
        filter_group = FilterGroup(
            filters=[Filter(property_name='email', operator='EQ', value=email)]
        )

        results = self.client.crm.contacts.search_api.do_search(
            public_object_search_request=PublicObjectSearchRequest(filter_groups=[filter_group])
        ).results

        if len(results):
            return results

        results = self.client.crm.contacts.basic_api.create(
            simple_public_object_input=SimplePublicObject(dict(email=email))
        )

        return results
```

Does this seem reasonable? 

Am I using the SDK correctly? (Seems like a lot of different things to import in order to get or create a contact using their email)

Eventually, I'll set some additional properties on either the created contact or the found contact, but I'd like to make sure this example makes sense first.

Thanks for the assistance.

**Comment by atanasiuk-hubspot** [comment]
Hi, @wadewilliams 

There is no `get_or_create` method in [Contacts API](https://developers.hubspot.com/docs/api/crm/contacts) at this moment.

> Am I using the SDK correctly? (Seems like a lot of different things to import in order to get or create a contact using their email)

This is indeed a correct workaround for this.

**Comment by wadewilliams** [comment]
Thanks for your help.

**Comment by yfaktor** [comment]
> Hello,
> 
> Is this for production use?
> 
> The API docs referrenced in the README refer to v1 but as I understand this sdk interacts with the v3 api
> 
> The newer api docs available at https://developers.hubspot.com/docs/api all have raw python implementations as examples and do not use this sdk.
> 
> Where is someone to start with building a modern hubspot integration right now?

Yes, we need to remove that banner actually - thank you for pointing this out. In general the yellow banners at the yellow banners at the tops of the pages indicate what state they are in.
