### ISSUE TITLE
Support for Subscription Preferences?

### ISSUE THREAD

**Issue by njt1982** [HubSpot/hubspot-api-python#52]
https://developers.hubspot.com/docs/api/marketing-api/subscriptions-preferences

I don't see anything about this endpoint in the package - is it unsupported?

**Comment by atanasiuk-hubspot** [comment]
Hi, @njt1982, this new API is not yet supported

**Comment by plaurynovich-hubspot** [comment]
Please, use v3.8.2 to work with these endpoints.
