### ISSUE TITLE
JSON serialize contacts.get_all output

### ISSUE THREAD

**Issue by alanwill** [HubSpot/hubspot-api-python#6]
Hi, 

Is there a convenient way to JSON serialize the output from the `hubspot.crm.contacts.get_all` API? The `updated_at` and `created_at` dates are in datetime format by default, however interestingly enough the `hs_analytics_last_timestamp` property is already converted to string. I wish they were all strings. 

Anyway, is there a way to convert from the `SimplePublicObject` object?

**Comment by alanwill** [comment]
I should have done a bit more digging before I posted, I found the .dict() method in the code so I can use that.

**Comment by atanasiuk-hubspot** [comment]
Looks to be resolved. Feel free to reopen if any issues.

**Comment by ElianoMarques** [comment]
@alanwill can you kindly explain how you did overcome this issue?

**Comment by ElianoMarques** [comment]
@alanwill  can you help with an example? I see the .dict only for a single value not all output?

**Comment by atanasiuk-hubspot** [comment]
Similar issue: https://github.com/HubSpot/hubspot-api-python/issues/43#issuecomment-791259768
