### ISSUE TITLE
CRM Owners missing **kwargs for archived

### ISSUE THREAD

**Issue by simonprydden** [HubSpot/hubspot-api-python#64]
owners get_page function does not accept parameter archived like other crm items

https://github.com/HubSpot/hubspot-api-python/blob/5cb86c8b6c793409443f72e741ac6c55b5d1c16b/hubspot/crm/owners/api/default_api.py#L164

:param bool archived: Whether to return only results that have been archived.

import requests
url = "https://api.hubapi.com/crm/v3/owners/"
querystring = {"limit":"100",**"archived":"false"**,"hapikey":"YOUR_HUBSPOT_API_KEY"}
headers = {'accept': 'application/json'}
response = requests.request("GET", url, headers=headers, params=querystring)
print(response.text)

**Comment by plaurynovich-hubspot** [comment]
Hi, @simonprydden.

I checked it with this code:

```
from hubspot import HubSpot

api_client = HubSpot(api_key="YOUR_HUBSPOT_API_KEY")
api = api_client.crm.owners.default_api

print(api.get_page(archived=True))
```

It works fine for me. The method accepts param archived as well. Could you provide more details?

**Comment by simonprydden** [comment]
Ah, found the issue, the version installed was 3.7.2, just upgraded and worked fine.
