### ISSUE TITLE
types_api not available under crm/associations

### ISSUE THREAD

**Issue by lievcin** [HubSpot/hubspot-api-python#72]
Hi! 
I have been playing with the API today and has been quite smooth, except when I trying to query association types. 
I'm trying do something like this:

```api_client.crm.associations.types_api.get_all(from_object_type="deals", to_object_type="companies") ```

or this

```api_client.crm.associations.get_all(from_object_type="deals", to_object_type="companies")```

But then I realised that under `crm.associations`, the api only sees the batch_api methods and not the types_api ones, maybe something is missing?

![Screenshot 2021-09-24 at 18 37 39](https://user-images.githubusercontent.com/729113/134717572-15de4409-0833-4ded-b753-ea8385e53a67.png)

Many thanks!

**Comment by nullcool** [comment]
Something similar happen to me, 

client.cms.blogs.blog_posts

turns into a hubspot.discovery.cms.blogs.blog_posts.discovery.Discovery object
that does not contain blog_posts_api

so:
client.cms.blogs.blog_posts.blog_posts_api.get_page()
will not work throwing this error: 

AttributeError: 'Discovery' object has no attribute ‘blog_posts_api'

**Comment by plaurynovich-hubspot** [comment]
Hi, types_api should be available now.
Hi @nullcool. It doesn't look related, but it should be
```python
client.cms.blogs.blog_posts.blog_post_api.get_page()
```
Thank you.

**Comment by noreallyimfine** [comment]
I don't see the types_api under crm.associations

![HubspotDealSoraInfoToCompanyStudentInfo - Jupyter Notebook 8-19-2022 1-22-56 PM](https://user-images.githubusercontent.com/48383940/185701249-63ac5093-da10-4b27-9413-79eeececab6b.png)

hubspot version: 6.0.0
