### ISSUE TITLE
AssociationType has gone, again

### ISSUE THREAD

**Issue by yuekui** [HubSpot/hubspot-api-python#74]
Related issue:
#60 
Related commit:
https://github.com/HubSpot/hubspot-api-python/commit/bf961812eb5fb5052a48b872814b7c732ddf57fe#diff-6d0dcad18583ecb8075ed89966adc0fb9399ec96360a8381550aed70b99b375b

**Comment by plaurynovich-hubspot** [comment]
Hi, @yuekui. It should be fixed in 4.0.1. Thank you.

**Comment by yuekui** [comment]
https://github.com/HubSpot/hubspot-api-python/commit/a6993cfdb41f73ef8f6889842c68e335039d992f#diff-f4944b1bf62bda690f5889d8b5938eeb4fcfd8e128b7b0b2ddb6316c207b25c5
Broke this import issue again.

**Comment by yuekui** [comment]
@plaurynovich-hubspot @alzheltkovskiy-hubspot

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @yuekui.
Thank you for reporting this issue.
We have fixed it in the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.2.2)

**Comment by yuekui** [comment]
@alzheltkovskiy-hubspot thanks for the quick fix, since this issue has been caused by regen for several times, do you think it would be a good idea to add a unit test to prevent it in the future?

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @yuekui .
We have already added new test coverage, thank you for your participation.
You may check out the new version [here](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.3.0).
Can i close this issue?

**Comment by yuekui** [comment]
Thanks @alzheltkovskiy-hubspot
