### ISSUE TITLE
Custom Object does not have get_all method

### ISSUE THREAD

**Issue by zscrape** [HubSpot/hubspot-api-python#77]
There is currently no way to get all records for a custom object, the get_all method is missing. Is that intentional? 

Can this be added to discovery/crm/objects/discovery.py?
```
    def get_all(self, **kwargs):
        return fetch_all(self.basic_api, **kwargs)
```

**Comment by plaurynovich-hubspot** [comment]
Hi, @zscrape. It was added in 4.0.2 version. Thank you.

**Comment by TommyMorrissey** [comment]
api_client = HubSpot(api_key= my_key)
custom_objects = api_client.crm.objects.get_all()

Currently using the above but getting error (name 'fetch_all' is not defined). I don't know any of the custom object names,, can I not just pull all of them? Or is there a way to pull the custom object names?

**Comment by plaurynovich-hubspot** [comment]
Hi, @zscrape, @TommyMorrissey. Since objects api uses object type as a param we can't actually use basic fetch_all method. So for now you can use get_all('object_type') method since v4.0.4. Thank you.

```python
api_client = HubSpot(api_key= your_key)
contacts = api_client.crm.objects.get_all('contacts')
companies = api_client.crm.objects.get_all('companies')
```

**Comment by TommyMorrissey** [comment]
I was not asking the right question but I found what I wanted on the API documentation pages, thank you!
