### ISSUE TITLE
CRM Contacts API - gdpr_delete file does not exist despite being imported in tutorials

### ISSUE THREAD

**Issue by michalrudko** [HubSpot/hubspot-api-python#78]
In GDPR deletions sample Python code in [CRM Contacts API](https://developers.hubspot.com/docs/api/crm/contacts) you have an import statement:
`from hubspot.crm.contacts.gdpr_delete import PublicGdprDeleteInput, ApiException`
that corresponds to a file `gdpr_delete` that does not exists, here's the GitHub path:
https://github.com/HubSpot/hubspot-api-python/tree/master/hubspot/crm/contacts
Could anyone explain how this API could be used at the moment? Thanks!

**Comment by alemor10** [comment]
lol why would include these in your codebase if they don't work .....

**Comment by alemor10** [comment]
@michalrudko  thanks for providing an alternative
