### ISSUE TITLE
Subscription API - hubspot.communication_preferences.subscribe path does not exist

### ISSUE THREAD

**Issue by michalrudko** [HubSpot/hubspot-api-python#79]
The path:
```
from hubspot.communication_preferences.subscribe import PublicUpdateSubscriptionStatusRequest, ApiException
```
mentioned in the tutorial below:
https://developers.hubspot.com/docs/api/marketing-api/subscriptions-preferences
does not exist. Is it a bug or this refers to some unreleased change?
It would be great if the code published in the official Hubspot webpages would be in sync with latest package version (there's a similar issue with the [GDPR deletion endpoint](https://github.com/HubSpot/hubspot-api-python/issues/78)).

**Comment by plaurynovich-hubspot** [comment]
Hi, @michalrudko. Looks like the code snippet refers to unreleased changes. I absolutely agree that it should be in sync and I hope it will be. Thank you.

**Comment by alfonso-techgc** [comment]
I'm experiencing the same issue. Are there plans to release the changes soon? It is now just over a year since this issue was opened. Thanks

**Comment by alfonso-techgc** [comment]
Never mind... I think I was using the wrong package.

Originally I installed the hubspot package like this:
`pip install hubspot`. 

The above is wrong. The sample code worked for me when installed this way instead:
`pip install --upgrade hubspot-api-client`
