### ISSUE TITLE
Hubspot Filemanager Api

### ISSUE THREAD

**Issue by mahi008** [HubSpot/hubspot-api-python#8]
Hello, I've started using this package for my project (Thanks BTW).
And I'm wondering if Hubspot Filemanager api is  available in this package ?
I can't find any example in Readme nor in the sample-apps directory.

Thank you !

**Comment by atanasiuk-hubspot** [comment]
Hi, @mahi008, Are you asking about https://developers.hubspot.com/docs/api/cms/files?

As soon as it's ready it will be added to SDK

**Comment by mahi008** [comment]
Yes @atanasiuk-hubspot , my bad, I didn't notice the message which states it's under development.

But one more quick question though, does the SDK has any detailed documentation ? 
I was trying to create "Hubspot Engagement", but I haven't found any documentation or anything related on creating an  "Engagement"  in Readme either.

**Comment by atanasiuk-hubspot** [comment]
> But one more quick question though, does the SDK has any detailed documentation ?
> I was trying to create "Hubspot Engagement", but I haven't found any documentation or anything related on creating an "Engagement" in Readme either.

No detailed documentation at this moment.
 
The idea is to follow 1:1 [HubSpot Apis](https://developers.hubspot.com/docs/api/overview). So for engagement methods it would be `crm.engagements` path. Following this principle no need to create detailed documentation for every method.

BTW [CRM Engagments API](https://developers.hubspot.com/docs/api/crm/engagements) is also under development.

**Comment by mahi008** [comment]
Thank you @atanasiuk-hubspot 😊, I'll close this issue as the solution depends on Hubspot's API (stable) release date.
