### ISSUE TITLE
api key issue

### ISSUE THREAD

**Issue by TommyMorrissey** [HubSpot/hubspot-api-python#82]
Hello, I developed a get request for some data from my companies HubSpot page. It works fine in one environment, but when trying to run the exact same code in another environment I get the following error (You must include a hapi_key or access_token attribute when initalizing the API). 
code below. I have already checked the python versions and additional libraries (simplejson, delorean), it's not those. I have no idea what is causing this. Any ideas?
from hubspot import HubSpot
api_client = HubSpot(api_key= 'my key')

**Comment by plaurynovich-hubspot** [comment]
Hi, @TommyMorrissey. It looks like the actual request doesn't use your api_key. Are you really sure that all versions are the same (including the sdk)? Could you investigate it a bit more, please? I'll need to reproduce it to help. Thank you.

**Comment by TommyMorrissey** [comment]
I investigated a bit more, couldn't find a difference, so tried the age-old uninstall and reinstall. That seemed to do the trick, not sure what happened when it downloaded. Thank you!

**Comment by kylepolich** [comment]
I am having this problem also.  The code was working, now did a `pip install --upgrade` and now it stopped.  It seems like a mistake to close this bug without a fix.

**Comment by janwirth** [comment]
I had this issue when installing `hubspot` instead of `hubspot-api-python`.
