### ISSUE TITLE
Get all contacts Legacy - Does not return a specific contact

### ISSUE THREAD

**Issue by jesusenlanet** [HubSpot/hubspot-api-python#85]
Hello,

Today 19/11/2021, we can see on the web app a contact created yesterday at `18/11/2021 10:03 GMT+1`
Everything seems fine for this customer in the HubSpot web application, the contact is not deleted and it seems to work correctly.

Also we are querying some v1 endpoints:
```
We use this endpoint to obtain the contact IDs
https://legacydocs.hubspot.com/docs/methods/contacts/get_contacts
/contacts/v1/lists/all/contacts/all

Later we use this method to obtain the contacts with info that we need
https://legacydocs.hubspot.com/docs/methods/contacts/get_batch_by_vid
/contacts/v1/contact/vids/batch/
```

We get this contact using `get_batch_by_vid` but this contact is not returned using `get_contacts`.

Our process need to query both endpoints because we are interested in some fields returned by `get_batch_by_vid`, but not present in other endpoints.

Due to the limitations of the get recently updated and created contacts endpoint (30 days and a limit of 10k), we are unable to use it.

We had a doubt that we had paging problems on our side, but we have checked in different ways and we are not able to get this contact.

This is an example script we used to test paging, the script stores the returned contacts in different files, we couldn't find any problems on our side:

```python
import json
from time import sleep

import requests

limit_per_request = 100
url = "https://api.hubapi.com/contacts/v1/lists/all/contacts/all"
params = {"hapikey": ":)", "count": limit_per_request}
vid_offset = None
batch = 0

while True:
    print(f"Page {batch}")
    sleep(0.30)
    if vid_offset is not None:
        params["vidOffset"] = vid_offset

    response = requests.get(url=url, params=params)

    response.raise_for_status()
    json_response = response.json()
    has_more = json_response.get("has-more", False)
    vid_offset = json_response.get("vid-offset", None)
    contacts = json_response.get("contacts", [])
    with open(f"contacts_batch_{batch}.json", "w") as fd:
        fd.write(json.dumps(contacts))

    batch += 1

    if not has_more:
        break
```

Also on the endpoint documentation we can read:

> Deduplication
> The primary identifier for a contact in HubSpot is an email address. The Contacts API automatically de-duplicates email addresses in HubSpot.

We tried to find this contact looking for the email, in case it goes through a deduplication process, but we are also unable to match this contact by email.

I would really appreciate any help or clarification on how these endpoints behave (have they any delay on the background?).

Thank you very much.

**Comment by plaurynovich-hubspot** [comment]
Hi, @jesusenlanet. Thank you for your question, but this is a python sdk for the v3 api

**Comment by jesusenlanet** [comment]
> Hi, @jesusenlanet. Thank you for your question, but this is a python sdk for the v3 api

Hi @plaurynovich-hubspot

Could you tell us which is the right place?

To put you in context we are a company acting on behalf of different clients, we get data from their APIs on HubSpot.
We don't have a HubSpot account, it would be great if we could be directed to the right place where we could open a support case.

**Comment by plaurynovich-hubspot** [comment]
Hi, @jesusenlanet. Please, try to check existing questions [here](https://community.hubspot.com/) or ask a new one. Thank you.
