### ISSUE TITLE
Properties with History?

### ISSUE THREAD

**Issue by TommyMorrissey** [HubSpot/hubspot-api-python#87]
Hello,
In V1 of the HubSpot API, there is a propertiesWithHistory parameter. Does this exist in this Python library for the current version? Or is there a way to replicate it? https://legacydocs.hubspot.com/docs/methods/deals/get-all-deals

Thank you in advance! Please let me know if you have any clarifying questions

**Comment by plaurynovich-hubspot** [comment]
Hi, @TommyMorrissey. We'll be able to support it for the v3 api, but it doesn't look like it's supported according to https://community.hubspot.com/t5/APIs-Integrations/API-v3-Properties-History-Available/td-p/365099. Thank you.

**Comment by TommyMorrissey** [comment]
got ya, thank you! Would you be able to provide an example of how to include the parameter or point me to the documentation for it in this library? I'm not able to find anything in the documentation for this library, tried a couple of different things and was unsuccessful.

**Comment by TommyMorrissey** [comment]
Nevermind, got it to work, thank you!

**Comment by rykermorgan** [comment]
@TommyMorrissey can you help me understand how you got this working?
