### ISSUE TITLE
Create a contact and associate it with a company sometimes fails

### ISSUE THREAD

**Issue by agustinleiraCDS** [HubSpot/hubspot-api-python#88]
Hello, to associate a contact with a company I am using the following code:
```
from hubspot import HubSpot
from hubspot.crm.contacts import PublicObjectSearchRequest, SimplePublicObjectInput, ApiException

def associateContactWithCompany(contact_id, company_id):
    try:
        return api_client.crm.contacts.associations_api.create(contact_id=contact_id, to_object_type="company", to_object_id=company_id, association_type="contact_to_company")
    except ApiException as e:
        print("Exception when calling associations_api->create: %s\n" % e)
```
Most of the times works fine, the issue comes when I create the user and the company at "the same time", sometimes this association doesn't work, I don't get any error but when I check in Hubspot's web console I see that the contact company is not the one I set, instead the one I chose I get the one that corresponds to the contact's email. I think there is a race condition, the association should be performing before the contact or the company is available on Hubspot. Have anyone had this kind of issue before? is there a way to overcome this?

Thanks

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @agustinleiraCDS. It works well for us. We couldn't reproduce your problem. Could you show us more code?
