### ISSUE TITLE
It's possiblite change "host" of API?

### ISSUE THREAD

**Issue by thiagoheron** [HubSpot/hubspot-api-python#89]
I need to change host of API, because I'm using a proxy to redirect the requests to my host, and this host redirect to host of Hubspot. It's possible?

**Comment by plaurynovich-hubspot** [comment]
Hi @thiagoheron. You can try to do something like this
```python
hubspot = HubSpot(api_key=your_api_key)
api = hubspot.crm.companies.basic_api
api.api_client.configuration.host = 'https://your.host.com/'
api.get_page()
```

**Comment by thiagoheron** [comment]
It works well, thank you @plaurynovich-hubspot !
