### ISSUE TITLE
Client does not include beta API `crm/calls`

### ISSUE THREAD

**Issue by mattotodd** [HubSpot/hubspot-api-python#91]
The Hubspot API documents Engagement objects like Calls here: https://developers.hubspot.com/docs/api/crm/calls

These endpoints do not appear in the current master but the documentation mentions they are `beta` so i'm assuming that is why they are not in the client (or i just cant find them).

Is there a way to build the python client and include these beta api calls?

**Comment by plaurynovich-hubspot** [comment]
Hi @mattotodd, @laurent-leconte crm.objects.calls should be available since 5.0.0. Thank you.
