### ISSUE TITLE
Webhook signature v3 support

### ISSUE THREAD

**Issue by 1ace** [HubSpot/hubspot-api-python#92]
Should `hubspot.utils.webhooks.validate_signature()` be upgraded to support v3 of the webhook signatures?

https://developers.hubspot.com/changelog/introducing-version-3-of-webhook-signatures

The announcement says:
> Prior versions of the X-HubSpot-Signature header will continue to be included for backward compatibility.

But there's no indication of how long they'll keep the v2 signature, so I'm not sure whether we can rely on always having a v2 signature and the current code being enough, or if someday they'll pull the plug on v2 and any code that doesn't support v3 but is still deployed somewhere will fail :shrug:

**Comment by alzheltkovskiy-hubspot** [comment]
Hi @1ace.
Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v7.3.0)?
Thank you.

**Comment by 1ace** [comment]
@alzheltkovskiy-hubspot I'm glad to hear that 💪
Unfortunately I have moved to another job in the meantime (and I don't interact with HubSpot at my new job), so I can't test this.

Perhaps one of the people watching the issue can test this; if you haven't heard back after a while feel free to close the issue 🙂
