### ISSUE TITLE
Library not honoring HTTPS_PROXY

### ISSUE THREAD

**Issue by calve** [HubSpot/hubspot-api-python#96]
Hi, I'm trying to run a script using this library on a server that cannot access the internet directly but must honor a corporate HTTP forward proxy.

It looks like there is a configuration option to set a URL but it does not appear to do anything nor it is documented https://github.com/HubSpot/hubspot-api-python/blob/3b68d9a594d43e916ceff0a8f868189accc565c1/hubspot/auth/oauth/rest.py#L93 ? 

How can I configure the hubspot-api-python to honor the `HTTP_PROXY` environment variable ?

**Comment by floridene** [comment]
Hey, 
any news regarding the proxy issue? 
We are running into the same problem as some of our infrastructure is hidden behind a proxy and we run your library. 

Can this not just be solved by adding this to the DiscoveryBase: 

`      
       if "proxy" in config:
            configuration.proxy = config["proxy"]
            configuration.proxy_headers = 'https'
   `

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @calve. Could you check the latest [version](https://github.com/HubSpot/hubspot-api-python/releases/tag/v11.0.0)?
