### ISSUE TITLE
Files check_import returns None 

### ISSUE THREAD

**Issue by alemor10** [HubSpot/hubspot-api-python#98]
I am using the files.check_import function to check if a file has finished uploading. Before the 25th of this month if it wasn't finishing or "pending" it would return a HubSpotCheckImportStatusResponse, but as of that date it is seems to return None until the file's status is complete. Is there a reason for that?
![Image from iOS](https://user-images.githubusercontent.com/43051685/165794517-86871a61-a565-4336-a5ae-ed4ee3713e4b.jpg)

**Comment by alzheltkovskiy-hubspot** [comment]
Hey @alemor10. I couldn't find any mention of HubSpotCheckImportStatusResponse in SDK versions older than 3. It's possible that you were using an earlier version where HubSpotCheckImportStatusResponse was utilized. However, it has now been decided to return None in cases where there is nothing to return.
