### ISSUE TITLE
How to use SimplePublicObjectWithAssociations for API

### ISSUE THREAD

**Issue by darless** [HubSpot/hubspot-api-python#99]
The model SimplePublicObjectWithAssociations exists, but does not seem to be used anywhere. Most of the <API>.create() functionality takes in SimplePublicObjectInput as an argument. This means if I need to also associate the object with another object I need the caller to make 2 calls instead of 1. 

Example:
To create a deal in a company:
- Need to define the properties of the deal, then create it (client.crm.deals.basic_api.create)
- Need to create an association from deal to the company (client.crm.deals.associations_api.create)

Instead, I would like:
```
from hubspot.crm.deals import SimplePublicObjectWithAssociation
obj = SimplePublicObjectWithAssociation(properties=properties, associations=associations)
client.crm.deals.basic_api.create(simple_public_object_with_association=obj)
```

**Comment by alemor10** [comment]
I don't think thats going to work the function currently takes SimplePublicObjectInput as a param, but I do admit this would be a nice feature/upgrade.

**Comment by alzheltkovskiy-hubspot** [comment]
Hi everyone.
The `SimplePublicObjectWithAssociation` object is returned in the response.
But as you rightly noted at the moment, most functions take as an argument only `SimplePublicObjectInput`.
I hope this information will be useful.

**Comment by dbeybia** [comment]
Hi everyone.
Anyone has an idea on how to pass the object association to the create call? Per the docs, adding an associations object is possible but I can't find the argument.
